# Прогноз дохода клиентов

 - Задача прогнозирования дохода имеет особенное значение в Банке. 
Эта информация помогает точнее и более релевантно подбирать продукты и условия их приобретения, что в свою очередь вносит существенный вклад в прибыль Банка. 
 - Помимо ценности для Банка, оценка дохода является регуляторным требованием ЦБ в части расчета предельно допустимой кредитной нагрузки для клиента (далее ПДН)

# Импорт библиотек

In [1]:
import os
import sys
import pandas as pd
import matplotlib.pyplot as plt

# Импорт функций

In [2]:
sys.path.append('../src') 

from preprocessing import (
    analyze_missing_columns,
    analyze_rows_statistics, 
    convert_basic_columns,
    analyze_realistic_selection,
    identify_problem_features,
    convert_numeric_strings,
    RobustAutoDataPreprocessor, 
    quick_preprocess,
    AdvancedSalaryEnricher
)

from data_explorer import DataExplorer

# Создание датафреймов

In [3]:
data_train = pd.read_csv('../data/hackathon_income_train.csv', sep=';')
data_test = pd.read_csv('../data/hackathon_income_test.csv', sep=';')
data_salary = pd.read_csv('../data/znr-2023.csv', sep=',')

# Первичный анализ данных

In [4]:
data_train.info(verbose='True', show_counts='True')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76786 entries, 0 to 76785
Data columns (total 224 columns):
 #    Column                                                                                           Non-Null Count  Dtype
---   ------                                                                                           --------------  -----
 0    id                                                                                               76786 non-null  int64
 1    dt                                                                                               76786 non-null  object
 2    target                                                                                           76786 non-null  object
 3    turn_cur_cr_avg_act_v2                                                                           59078 non-null  object
 4    salary_6to12m_avg                                                                                14875 non-null  object
 5    hdb_bki_total_max_limit                                                                          67413 non-null  float64
 6    dp_ils_paymentssum_avg_12m                                                                       16503 non-null  object
 7    hdb_bki_total_cc_max_limit                                                                       63041 non-null  float64
 8    incomeValue                                                                                      63817 non-null  object
 9    gender                                                                                           76786 non-null  object
 10   avg_cur_cr_turn                                                                                  60214 non-null  object
 11   adminarea                                                                                        57223 non-null  object
 12   turn_cur_cr_avg_v2                                                                               59432 non-null  object
 13   turn_cur_cr_max_v2                                                                               59432 non-null  object
 14   hdb_bki_total_pil_max_limit                                                                      62001 non-null  float64
 15   age                                                                                              76786 non-null  object
 16   dp_ils_avg_salary_1y                                                                             15926 non-null  object
 17   turn_cur_cr_sum_v2                                                                               59432 non-null  object
 18   by_category__amount__sum__eoperation_type_name__ishodjaschij_bystryj_platezh_sbp                 31744 non-null  object
 19   turn_cur_db_sum_v2                                                                               59432 non-null  object
 20   turn_cur_db_avg_act_v2                                                                           58580 non-null  object
 21   dp_ils_avg_salary_2y                                                                             16302 non-null  object
 22   curr_rur_amt_cm_avg                                                                              58785 non-null  object
 23   turn_cur_db_avg_v2                                                                               59432 non-null  object
 24   by_category__amount__sum__eoperation_type_name__vhodjaschij_bystryj_platezh_sbp                  29934 non-null  object
 25   dp_ils_paymentssum_avg_6m                                                                        16503 non-null  object
 26   avg_cur_db_turn                                                                                  60214 non-null  object
 27   hdb_bki_active_cc_max_limit                                                                      56866 non-null  float64
 28   incomeValueCategory                                                                              63817 non-null  object
 29   avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate               41887 non-null  object
 30   avg_credit_turn_rur                                                                              60214 non-null  object
 31   dp_ils_salary_ratio_1y3y                                                                         15842 non-null  object
 32   by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona                       38655 non-null  object
 33   turn_cur_cr_7avg_avg_v2                                                                          59432 non-null  object
 34   dp_ils_accpayment_avg_12m                                                                        16503 non-null  object
 35   curbal_usd_amt_cm_avg                                                                            76080 non-null  object
 36   avg_by_category__amount__sum__cashflowcategory_name__supermarkety                                47752 non-null  object
 37   avg_loan_cnt_with_insurance                                                                      19202 non-null  object
 38   avg_by_category__amount__sum__cashflowcategory_name__gipermarkety                                45111 non-null  object
 39   city_smart_name                                                                                  67323 non-null  object
 40   uniV5                                                                                            63817 non-null  object
 41   turn_cur_db_max_v2                                                                               59432 non-null  object
 42   avg_by_category__amount__sum__cashflowcategory_name__kafe                                        46909 non-null  object
 43   turn_other_db_max_v2                                                                             48039 non-null  object
 44   turn_cur_cr_min_v2                                                                               59432 non-null  object
 45   hdb_bki_other_active_pil_outstanding                                                             35622 non-null  float64
 46   dp_ewb_last_employment_position                                                                  15081 non-null  object
 47   turn_cur_db_min_v2                                                                               59432 non-null  object
 48   hdb_bki_total_products                                                                           70561 non-null  float64
 49   per_capita_income_rur_amt                                                                        69392 non-null  object
 50   avg_debet_turn_rur                                                                               60214 non-null  object
 51   hdb_relend_active_max_psk                                                                        67302 non-null  object
 52   dda_rur_amt_curr_v2                                                                              73166 non-null  object
 53   mob_cnt_days                                                                                     54689 non-null  object
 54   dp_ils_days_from_last_doc                                                                        16503 non-null  object
 55   avg_6m_money_transactions                                                                        55130 non-null  object
 56   transaction_category_supermarket_percent_cnt_2m                                                  42413 non-null  object
 57   pil                                                                                              73118 non-null  object
 58   hdb_bki_total_max_overdue_sum                                                                    67257 non-null  float64
 59   avg_6m_clothing                                                                                  55130 non-null  object
 60   avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi                           39673 non-null  object
 61   addrref                                                                                          68237 non-null  object
 62   bki_total_auto_cnt                                                                               64965 non-null  float64
 63   dp_payoutincomedata_payout_avg_3_month                                                           10931 non-null  object
 64   hdb_outstand_sum                                                                                 67392 non-null  object
 65   avg_3m_money_transactions                                                                        55130 non-null  object
 66   dp_address_unique_regions                                                                        14972 non-null  object
 67   min_balance_rur_amt_6m_af                                                                        11133 non-null  object
 68   transaction_category_supermarket_sum_cnt_m3_4                                                    40307 non-null  object
 69   dp_payoutincomedata_payout_max_3_month                                                           10931 non-null  object
 70   hdb_bki_total_ip_max_limit                                                                       20809 non-null  float64
 71   hdb_bki_total_cnt                                                                                70483 non-null  float64
 72   blacklist_flag                                                                                   76080 non-null  object
 73   bki_total_oth_cnt                                                                                64965 non-null  float64
 74   dp_payoutincomedata_payout_sum_3_month                                                           10931 non-null  object
 75   hdb_relend_outstand_sum                                                                          67397 non-null  object
 76   total_rur_amt_cm_avg                                                                             58785 non-null  object
 77   mob_cover_days                                                                                   54689 non-null  object
 78   dp_payoutincomedata_payout_max_6_month                                                           10931 non-null  object
 79   label_Below_50k_share_r1                                                                         34010 non-null  object
 80   turn_fdep_db_sum_v2                                                                              3836 non-null   object
 81   dp_ils_accpayment_avg_6m_current                                                                 16503 non-null  object
 82   transaction_category_cash_percent_amt_2m                                                         25586 non-null  object
 83   curr_rur_amt_3m_avg                                                                              70301 non-null  object
 84   transaction_category_restaurants_sum_amt_m2                                                      21017 non-null  object
 85   loan_cnt                                                                                         19202 non-null  object
 86   turn_fdep_db_avg_v2                                                                              3836 non-null   object
 87   turn_cur_db_7avg_avg_v2                                                                          59432 non-null  object
 88   bki_total_ip_max_outstand                                                                        14457 non-null  float64
 89   amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate  29141 non-null  object
 90   profit_income_out_rur_amt_12m                                                                    76176 non-null  object
 91   avg_6m_hotels                                                                                    55130 non-null  object
 92   hdb_ovrd_sum                                                                                     67379 non-null  object
 93   dp_ils_total_seniority                                                                           16683 non-null  object
 94   dp_ils_paymentssum_avg_6m_current                                                                16503 non-null  object
 95   smsInWavg6m                                                                                      51965 non-null  object
 96   avg_fdep_db_turn                                                                                 60214 non-null  object
 97   device_iphone_avg                                                                                54689 non-null  object
 98   by_category__amount__sum__eoperation_type_name__platezh_za_mobilnyj_cherez_ps                    24530 non-null  object
 99   avg_balance_rur_amt_1m_af                                                                        11133 non-null  object
 100  curr_rur_amt_cm_avg_period_days_ago_v2                                                           73166 non-null  object
 101  avg_by_category__amount__sum__cashflowcategory_name__oteli                                       8861 non-null   object
 102  hdb_bki_total_ip_cnt                                                                             67413 non-null  float64
 103  hdb_bki_active_cc_max_outstand                                                                   56696 non-null  float64
 104  hdb_other_outstand_sum                                                                           60869 non-null  object
 105  days_to_last_transaction                                                                         66585 non-null  object
 106  hdb_bki_total_pil_max_overdue                                                                    61233 non-null  float64
 107  vert_pil_last_credit_step_screen_view_3m                                                         57298 non-null  object
 108  acard                                                                                            73118 non-null  object
 109  bki_total_il_max_limit                                                                           47188 non-null  float64
 110  other_credits_count                                                                              73057 non-null  object
 111  tz_msk_timedelta                                                                                 57223 non-null  object
 112  turn_save_db_min_v2                                                                              16436 non-null  object
 113  profit_income_out_rur_amt_9m                                                                     76176 non-null  object
 114  dp_ils_ipkcurrentyear_currentyearpensfactor                                                      13432 non-null  object
 115  avg_by_category__amount__sum__cashflowcategory_name__odezhda                                     35170 non-null  object
 116  cntOnnRinCallAvg6m                                                                               11865 non-null  object
 117  dda_rur_amt_3m_avg                                                                               70301 non-null  object
 118  winback_cnt                                                                                      76080 non-null  object
 119  salary_median_in_gex_r1                                                                          34010 non-null  object
 120  dp_payoutincomedata_payout_avg_prev_year                                                         7871 non-null   object
 121  avg_amount_daily_transactions_90d                                                                51783 non-null  object
 122  vert_has_app_ru_tinkoff_investing                                                                57298 non-null  object
 123  transaction_category_supermarket_inc_cnt_2m                                                      42413 non-null  object
 124  vert_pil_sms_success_3m                                                                          57298 non-null  object
 125  min_balance_rur_amt_1m_af                                                                        11133 non-null  object
 126  dp_ils_max_seniority                                                                             16588 non-null  object
 127  avg_by_category__amount__sum__cashflowcategory_name__set_supermarketov                           9569 non-null   object
 128  label_500k_to_1M_share_r1                                                                        34010 non-null  object
 129  avg_by_category__amount__sum__cashflowcategory_name__zarubezhnye_finansovye_operatsii            5568 non-null   object
 130  bki_total_products                                                                               64965 non-null  float64
 131  avg_6m_all                                                                                       55130 non-null  object
 132  dp_ils_avg_simultanious_jobs_5y                                                                  16478 non-null  object
 133  dp_ewb_dismissal_due_contract_violation_by_lb_cnt                                                16209 non-null  object
 134  summarur_1m_purch                                                                                55130 non-null  object
 135  diff_avg_cr_db_turn                                                                              60214 non-null  object
 136  dp_ils_cnt_changes_1y                                                                            16588 non-null  object
 137  dp_ils_employeers_cnt_last_month                                                                 16503 non-null  object
 138  dp_payoutincomedata_payout_avg_6_month                                                           10931 non-null  object
 139  dp_ewb_last_organization                                                                         12893 non-null  float64
 140  by_category__amount__sum__eoperation_type_name__perevod_mezhdu_svoimi_schetami                   25533 non-null  object
 141  bki_active_auto_cnt                                                                              64965 non-null  float64
 142  turn_other_cr_avg_act_v2                                                                         47357 non-null  object
 143  cntVoiceOutMob6m                                                                                 51965 non-null  object
 144  avg_by_category__amount__sum__cashflowcategory_name__puteshestvija                               10274 non-null  object
 145  loanacc_rur_amt_cm_avg                                                                           58785 non-null  object
 146  transaction_category_supermarket_sum_cnt_m2                                                      42413 non-null  object
 147  transaction_category_supermarket_sum_amt_d15                                                     34934 non-null  object
 148  avg_fdep_cr_turn                                                                                 60214 non-null  object
 149  transaction_category_restaurants_percent_cnt_2m                                                  21017 non-null  object
 150  bki_total_max_limit                                                                              59047 non-null  float64
 151  avg_by_category__amount__sum__cashflowcategory_name__reklama_v_internete                         5222 non-null   object
 152  transaction_category_restaurants_percent_amt_2m                                                  21017 non-null  object
 153  turn_fdep_db_avg_act_v2                                                                          2325 non-null   object
 154  dp_ils_accpayment_avg_6m                                                                         16503 non-null  object

In [5]:
pd.set_option('display.max_columns', None)
data_train.head(5)

,id,dt,target,turn_cur_cr_avg_act_v2,salary_6to12m_avg,hdb_bki_total_max_limit,dp_ils_paymentssum_avg_12m,hdb_bki_total_cc_max_limit,incomeValue,gender,avg_cur_cr_turn,adminarea,turn_cur_cr_avg_v2,turn_cur_cr_max_v2,hdb_bki_total_pil_max_limit,age,dp_ils_avg_salary_1y,turn_cur_cr_sum_v2,by_category__amount__sum__eoperation_type_name__ishodjaschij_bystryj_platezh_sbp,turn_cur_db_sum_v2,turn_cur_db_avg_act_v2,dp_ils_avg_salary_2y,curr_rur_amt_cm_avg,turn_cur_db_avg_v2,by_category__amount__sum__eoperation_type_name__vhodjaschij_bystryj_platezh_sbp,dp_ils_paymentssum_avg_6m,avg_cur_db_turn,hdb_bki_active_cc_max_limit,incomeValueCategory,avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate,avg_credit_turn_rur,dp_ils_salary_ratio_1y3y,by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona,turn_cur_cr_7avg_avg_v2,dp_ils_accpayment_avg_12m,curbal_usd_amt_cm_avg,avg_by_category__amount__sum__cashflowcategory_name__supermarkety,avg_loan_cnt_with_insurance,avg_by_category__amount__sum__cashflowcategory_name__gipermarkety,city_smart_name,uniV5,turn_cur_db_max_v2,avg_by_category__amount__sum__cashflowcategory_name__kafe,turn_other_db_max_v2,turn_cur_cr_min_v2,hdb_bki_other_active_pil_outstanding,dp_ewb_last_employment_position,turn_cur_db_min_v2,hdb_bki_total_products,per_capita_income_rur_amt,avg_debet_turn_rur,hdb_relend_active_max_psk,dda_rur_amt_curr_v2,mob_cnt_days,dp_ils_days_from_last_doc,avg_6m_money_transactions,transaction_category_supermarket_percent_cnt_2m,pil,hdb_bki_total_max_overdue_sum,avg_6m_clothing,avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi,addrref,bki_total_auto_cnt,dp_payoutincomedata_payout_avg_3_month,hdb_outstand_sum,avg_3m_money_transactions,dp_address_unique_regions,min_balance_rur_amt_6m_af,transaction_category_supermarket_sum_cnt_m3_4,dp_payoutincomedata_payout_max_3_month,hdb_bki_total_ip_max_limit,hdb_bki_total_cnt,blacklist_flag,bki_total_oth_cnt,dp_payoutincomedata_payout_sum_3_month,hdb_relend_outstand_sum,total_rur_amt_cm_avg,mob_cover_days,dp_payoutincomedata_payout_max_6_month,label_Below_50k_share_r1,turn_fdep_db_sum_v2,dp_ils_accpayment_avg_6m_current,transaction_category_cash_percent_amt_2m,curr_rur_amt_3m_avg,transaction_category_restaurants_sum_amt_m2,loan_cnt,turn_fdep_db_avg_v2,turn_cur_db_7avg_avg_v2,bki_total_ip_max_outstand,amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate,profit_income_out_rur_amt_12m,avg_6m_hotels,hdb_ovrd_sum,dp_ils_total_seniority,dp_ils_paymentssum_avg_6m_current,smsInWavg6m,avg_fdep_db_turn,device_iphone_avg,by_category__amount__sum__eoperation_type_name__platezh_za_mobilnyj_cherez_ps,avg_balance_rur_amt_1m_af,curr_rur_amt_cm_avg_period_days_ago_v2,avg_by_category__amount__sum__cashflowcategory_name__oteli,hdb_bki_total_ip_cnt,hdb_bki_active_cc_max_outstand,hdb_other_outstand_sum,days_to_last_transaction,hdb_bki_total_pil_max_overdue,vert_pil_last_credit_step_screen_view_3m,acard,bki_total_il_max_limit,other_credits_count,tz_msk_timedelta,turn_save_db_min_v2,profit_income_out_rur_amt_9m,dp_ils_ipkcurrentyear_currentyearpensfactor,avg_by_category__amount__sum__cashflowcategory_name__odezhda,cntOnnRinCallAvg6m,dda_rur_amt_3m_avg,winback_cnt,salary_median_in_gex_r1,dp_payoutincomedata_payout_avg_prev_year,avg_amount_daily_transactions_90d,vert_has_app_ru_tinkoff_investing,transaction_category_supermarket_inc_cnt_2m,vert_pil_sms_success_3m,min_balance_rur_amt_1m_af,dp_ils_max_seniority,avg_by_category__amount__sum__cashflowcategory_name__set_supermarketov,label_500k_to_1M_share_r1,avg_by_category__amount__sum__cashflowcategory_name__zarubezhnye_finansovye_operatsii,bki_total_products,avg_6m_all,dp_ils_avg_simultanious_jobs_5y,dp_ewb_dismissal_due_contract_violation_by_lb_cnt,summarur_1m_purch,diff_avg_cr_db_turn,dp_ils_cnt_changes_1y,dp_ils_employeers_cnt_last_month,dp_payoutincomedata_payout_avg_6_month,dp_ewb_last_organization,by_category__amount__sum__eoperation_type_name__perevod_mezhdu_svoimi_schetami,bki_active_auto_cnt,turn_other_cr_avg_act_v2,cntVoiceOutMob6m,avg_by_category__amount__sum__cashflowcategory_name__puteshestvija,loanacc_rur_amt_cm_avg,transaction_category_supermarket_sum_cnt_m2,transaction_category_supermarket_sum_amt_d15,avg_fdep_cr_turn,transaction_category_restaurants_percent_cnt_2m,bki_total_max_limit,avg_by_category__amount__sum__cashflowcategory_name__reklama_v_internete,transaction_category_restaurants_percent_amt_2m,turn_fdep_db_avg_act_v2,dp_ils_accpayment_avg_6m,turn_other_cr_sum_v2,client_active_flag,avg_by_category__amount__sum__cashflowcategory_name__produkty,curr_rur_amt_cm_avg_inc_v2,nonresident_flag,avg_by_category__amount__sum__cashflowcategory_name__kosmetika,vert_has_app_ru_vtb_invest,dp_ils_avg_salary_3y,hdb_bki_total_auto_max_limit,days_after_last_request,cntRegionTripsWavg1m,vert_has_app_ru_cian_main,loanacc_rur_amt_curr_v2,avg_3m_no_cat,vert_ghost_close_dpay3_last_days,vert_has_app_ru_raiffeisennews,dp_ils_days_ip_share_5y,avg_by_category__amount__sum__cashflowcategory_name__platezhi_cherez_internet,hdb_bki_total_micro_max_overdue,bki_total_active_products,by_category__amount__sum__eoperation_type_name__perevod_s_karty_na_kartu,calledCtnOutGroup,vert_pil_loan_application_success_3m,vert_pil_fee_discount_change_3m,businessTelSubs,profit_income_out_rur_amt_l2m,avg_3m_healthcare_services,dp_ils_paymentssum_month_avg,ovrd_sum,hdb_bki_total_active_products,hdb_bki_total_micro_cnt,hdb_bki_active_pil_cnt,loan_cur_amt,mob_total_sessions,period_last_act_ad,dp_ils_days_multiple_job_share_2y,hdb_bki_total_cc_max_overdue,lifetimeComp,hdb_bki_total_pil_last_days,amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__elektronnye_dengi,turn_save_cr_max_v2,hdb_bki_active_pil_max_limit,dp_ils_accpayment_avg_3m,avg_6m_restaurants,hdb_bki_total_pil_cnt,transaction_category_fastfood_percent_cnt_2m,hdb_bki_total_pil_max_del90,accountsalary_out_flag,cntBlockWavg6m,express_rur_amt_cm_avg,loanacc_rur_amt_cm_avg_inc_v2,hdb_bki_last_product_days,dp_ils_days_multiple_job_cnt_5y,dp_ils_accpayment_month_avg,cred_dda_rur_amt_3m_avg,avg_3m_all,hdb_other_active_max_psk,hdb_bki_other_active_ip_outstanding,total_sum,dp_ils_uniq_companies_1y,avg_6m_travel,avg_6m_government_services,hdb_bki_active_cc_max_overdue,total_rur_amt_cm_avg_period_days_ago_v2,label_Above_1M_share_r1,transaction_category_supermarket_sum_cnt_d15,max_balance_rur_amt_1m_af,w,first_salary_income
0,2,2024-04-30,"109324,47632478633","1465144,96",NaN,52800.0,"365346,244633755",23213.0,"97366,0",Женский,"124649,0",Свердловская область,"122095,41333333333","114798,72",52800.0,"40,0","128940,18082054095","1465144,96","32105,342465753427","1476118,3599999987","1476118,3599999987","122640,14305860807","14031,0","123009,86333333323","1495,890410958904","314012,3479341766","125331,0",13000.0,"5,0","3690,41095890411","124649,0","1,2577543391890502","364,9315068493151","15000,0","58447,06530723358","0,0","6760,307671232876",NaN,"9506,73452054795",Екатеринбург,"0,0192031","79788,73","2007,123287671233",NaN,"1465144,96",NaN,ВРАЧ-ДЕРМАТОВЕНЕРОЛОГ,"1476118,3599999987",6.0,"63119,0","125331,0","24,05","245,0","77,0","-274,0","2383,0","0,5142857142857142","0,0",20739.00,"680,0",NaN,Свердловская область,0.0,"136132,46","0,0","4767,0",66,NaN,"29,0","159782,95",NaN,38.0,"0,0",0.0,"408397,38","0,0","14031,0","0,8555555555555555","159782,95","0,25675675675675674",NaN,"50227,40528113384","0,1775386317234221","14532,0","1450,0",NaN,NaN,"2374,798",NaN,"14300,0","118,0","0,0","0,0","12,583162","314012,3479341766","39,1914","0,0","0,0","369,86301369863014",NaN,"297,0",NaN,0.0,0.0,"0,0","4,0",20739.0,"0,0","0,0",52800.0,"1,0","2,0",NaN,"17,88888888888889","4,056","3116,7123287671234",NaN,"14532,0","1,0","90651,12942226334","110826,295","1321,2354444444447","0,0","0,9647577092511012","0,0",NaN,"5804,0",NaN,"0,013513513513513514",NaN,3.0,"38410,0","1,185334872979","0,0","35729,0","-682,3800000000338","1,0","1,0","129814,96333333333",6.664012e+09,NaN,0.0,NaN,"120,3518","2589,0410958904113","0,0","36,0","8023,33","0,0","0,014285714285714285",52800.0,NaN,"0,01800216895097637",NaN,"50227,40528113384",NaN,"1,0","3085,5443835616443","9256,0","0,0","566,0728767123288","0,0","102516,18841854001",NaN,"3,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0",NaN,5000.00,1.0,NaN,NaN,"0,0","3,0","1,0","123,0","9703,0","208391,82215773733","0,0",1.0,1.0,0.0,NaN,"429,0",NaN,"0,0",0.0,"102,0",808.0,NaN,NaN,NaN,"56052,16912568309","1243,0",2.0,"0,1",0.0,"1,0","0,0259","0,0","0,0",808.0,"412,0","32743,321019924973","0,0","39637,0","24,05",NaN,"0,0","1,0","0,0","57,0",0.0,"297,0","0,02702702702702703","9,0",NaN,"0,3012172807640372",NaN
1,4,2024-02-29,"25558,02866242038","303593,66",NaN,260200.0,NaN,10000.0,"32580,0",Женский,"63653,0",Краснодарский край,"75898,415","260200,0",260200.0,"43,0",NaN,"910780,98",NaN,"910465,61","303488,5366666667",NaN,"14580,0","75872,13416666667",NaN,NaN,"76801,0",0.0,"2,0","8328,07570977918","85873,0",NaN,NaN,"1000,0",NaN,"77,0","146,21451104100947","1,0","725,1350157728705",Краснодар,"0,0352203","141015,0","3813,0283911671927","260200,0","28000,0",NaN,NaN,"28000,0",5.0,"61725,0","81670,0","24,867","5739,0","54,0",NaN,"1667,0","0,5454545454545454","1,0",183478.00,"0,0","3237,1050473186124",Краснодарский край,0.0,NaN,"199003,453125","3333,0",NaN,NaN,"2,0",NaN,NaN,40.0,"0,0",0.0,NaN,"199003,453125","14580,0","0,6",NaN,NaN,NaN,NaN,"0,34750275830314403","30245,0",NaN,"1,0",NaN,"2141,306666666667",NaN,"10000,0","5678,090909090909","0,0","0,0",NaN,NaN,"172,2963","0,0","0,0",NaN,NaN,"30245,0",NaN,0.0,0.0,"0,0","8,0",183478.0,"0,0","0,0",260200.0,"1,0","0,0",NaN,"6939,888888888889",NaN,"149,7160883280757",NaN,"30245,0","0,0",NaN,NaN,"814,3804444444445","0,0","1,761111111111111","0,0",NaN,NaN,NaN,NaN,NaN,2.0,"17308,0",NaN,NaN,"13810,0","4202,993333333332",NaN,NaN,NaN,NaN,NaN,0.0,"36315,333333333336","104,0833",NaN,"141992,0","12,0","1374,04","0,0",NaN,260200.0,NaN,NaN,NaN,NaN,"108946,0","1,0","2339,3782334384855","-1710,0","0,0",NaN,"0,0",NaN,NaN,"1,0","32,875","0,0","194603,0","0,0","0,0","0,0",NaN,NaN,NaN,2.0,NaN,NaN,"0,0","0,0","0,0","2709,0","446,0",NaN,"0,0",2.0,0.0,1.0,NaN,"182,0",NaN,NaN,67.0,"55,0",217.0,NaN,NaN,260200.0,NaN,"3075,0",3.0,"0,045454545454545456",15.0,"1,0","0,4444","0,0","-21973,0",217.0,NaN,NaN,"0,0","24431,0","0,0",NaN,"0,0",NaN,"0,0","707,0",67.0,"30245,0",NaN,"2,0",NaN,"0,6957996079578388",NaN
2,5,2024-02-29,"40666,753097982706","490754,01",NaN,2000000.0,NaN,90000.0,"96866,0",Женский,"404545,0",Новосибирская область,"122688,5025","265000,0",100000.0,"48,0",NaN,"1472262,03",NaN,"1399289,6100000008","466429,8700000003",NaN,"3866,0","116607,46750000007",NaN,NaN,"374919,0",90000.0,"5,0","2161,6438356164385","494787,0",NaN,NaN,"70185,0",NaN,"85,0","1866,240821917808",NaN,"54,82520547945205",Томск,"0,0198434","266449,7","1201,3167123287672","27,16","265000,0",NaN,NaN,"265000,0",5.0,"46059,0","374919,0","0,0","32455,0","72,0",NaN,"0,0","0,7777777777777778","0,0",368.00,"0,0",NaN,Томская область,0.0,NaN,"709889,375","0,0",NaN,NaN,"41,0",NaN,2000000.0,55.0,"0,0",0.0,NaN,"0,0","29521,0","0,8",NaN,"0,5098039215686274","0,0",NaN,NaN,"5083,0","6829,0",NaN,"0,0","13827,016666666668",709889.4,NaN,"120,83333333333333","0,0","0,0",NaN,NaN,NaN,"0,0","0,0",NaN,NaN,"5083,0",NaN,1.0,0.0,"709889,375","3,0",0.0,"0,0","1,0",NaN,"2,0","4,0",NaN,"115,77777777777777",NaN,NaN,"6,1667","5083,0","0,0","48366,33131868132",NaN,"691,8257777777782","0,0","2,0277777777777777","0,0",NaN,NaN,NaN,"0,0196078431372549",NaN,2.0,"13606,0",NaN,NaN,"36751,0","119867,85333333339",NaN,NaN,NaN,NaN,NaN,0.0,"13,585",NaN,"207,94520547945206","0,0","77,0","5112,000000000001","90242,0","0,020202020202020204",2000000.0,NaN,"0,1494725451175512",NaN,NaN,"27,17","1,0","2718,4117808219203","30214,0","0,0","246,78082191780823","0,0",NaN,NaN,"28,0",NaN,"0,0","0,0","0,0","0,0","0,0",NaN,NaN,NaN,2.0,NaN,"2,0","0,0","2,0",NaN,"109,0","1825,0",NaN,"0,0",2.0,0.0,0.0,NaN,"238,0",NaN,NaN,368.0,NaN,6061.0,NaN,NaN,NaN,NaN,"1363,0",2.0,"0,010101010101010102",0.0,"1,0","0,2041","0,0","0,0",1168.0,NaN,NaN,"0,0","20755,0","8,197",709889.375,"0,0",NaN,"422,0","0,0",0.0,"210322,0","0,0","20,0",NaN,"0,5159704060557002",NaN
3,6,2024-04-30,"43856,67205839414","219875,12",NaN,75000.0,NaN,75000.0,"43860,0",Мужской,"39988,0",Хабаровский край,"18322,926666666666","23000,0",29760.0,"47,0",NaN,"219875,12","8603,757225433526","214877,69999999992","214877,69999999992",NaN,"7817,0","17906,474999999995",NaN,NaN,"38587,0",60000.0,"3,0",NaN,"39988,0",NaN,"324,4508670520231","0,0",NaN,"0,0","371,93063583815035",NaN,"1748,765895953757",Хабаровск,"0,0135717","11000,0","2031,1560693641618",NaN,"219875,12",NaN,NaN,"214877,69999999992",8.0,"65161,0","38587,0","18,0","13477,0","38,0",NaN,"0,0","0,7777777777777778","0,0",620.24,"0,0","346,8208092485549",Хабаровский край,0.0,NaN,"37611,0","0,0",NaN,NaN,"58,0",NaN,NaN,36.0,"0,0",0.0,NaN,"37611,0","7817,0","0,4222222222222222",NaN,"0,6666666666666666",NaN,NaN,NaN,"5275,0","8170,0",NaN,NaN,"3089,8875",NaN,NaN,"189,16666666666666","0,0","0,0",NaN,NaN,NaN,"0,0","0,0","476,87861271676303",NaN,"7187,0",NaN,0.0,37611.0,"37611,0","2,0",0.0,"0,0","0,0",29760.0,"2,0","7,0",NaN,"189,16666666666666",NaN,NaN,"0,0","5275,0","0,0","39646,20888986687",NaN,"853,6193333333335","0,0","0,9967078189300411","0,0",NaN,NaN,NaN,"0,0",NaN,3.0,"22817,0",NaN,NaN,"29363,0","1401,479999999996",NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,"0,0","56,0","5110,97","0,0","0,027777777777777776",75000.0,NaN,"0,15541700551188217",NaN,NaN,NaN,"1,0","8666,630635838152","915,0","0,0","129,71098265895955","0,0",NaN,NaN,"6,0",NaN,"0,0","0,0","0,0","0,0","0,0",NaN,NaN,620.24,1.0,NaN,"2,0","0,0","2,0",NaN,"414,0","0,0",NaN,NaN,3.0,1.0,0.0,NaN,"82,0",NaN,NaN,312.0,NaN,1544.0,"2000,0",NaN,NaN,NaN,"1996,0",6.0,"0,013888888888888888",0.0,"1,0","0,0123","0,0","0,0",887.0,NaN,NaN,"0,0","25599,0","18,0",NaN,NaN,NaN,"0,0","0,0",0.0,"7187,0","0,0","7,0",NaN,"0,4780029003784456",NaN
4,7,2024-04-30,"130420,85199232883","1750241,8449999997",NaN,1000000.0,NaN,240000.0,"83815,0",Женский,"202439,0",Новосибирская область,"291706,9741666666","415000,0",1000000.0,"46,0",NaN,"3500483,6899999995","33254,10904109589","3449372,650000001","1724686,3250000004",NaN,"15053,0","287447,7208333334","8912,054794520549",NaN,"186292,0",240000.0,"5,0",NaN,"276007,0",NaN,"11338,27397260274","18750,0",NaN,"0,0","3451,950410958904",NaN,"5784,880273972603",Новосибирск,"0,0109003","419200,0","376,4383561643836",NaN,"415000,0",124714.828125,NaN,"415000,0",8.0,"51917,0","291591,0","24,05","185324,0","70,0",NaN,"0,0","0,5918367346938775","0,0",0.00,"7242,0","33,369863013698634",Новосибирская область,0.0,NaN,"124714,828125","0,0",NaN,NaN,"22,0",NaN,900000.0,28.0,"0,0",0.0,NaN,"124714,828125","211802,0","0,7777777777777778",NaN,"0,8928571428571429","0,0",NaN,NaN,"8620,0",NaN,NaN,"0,0","4154,084285714286",NaN,NaN,"406,8333333333333","0,0","0,0",NaN,NaN,"181,7519","0,0","0,0","544,1095890410959",NaN,"7931,0",NaN,1.0,0.0,"124714,828125","2,0",0.0,"0,0","0,0",1000000.0,"2,0","4,0","1071260,4700000002","551,0",NaN,"6122,465753424658",NaN,"259124,0","0,0","25680,415255851934",NaN,"4651,799000000001","0,0","1,2691846522781773","0,0",NaN,NaN,NaN,"0,0",NaN,3.0,"175246,0",NaN,NaN,"78151,0","-15584,283333333384",NaN,NaN,NaN,NaN,"106369,15561643837",0.0,NaN,"352,2143",NaN,"0,0","29,0","10205,890000000001","4935,0",NaN,1000000.0,NaN,NaN,NaN,NaN,NaN,"1,0","1139,1254794520548","-1254,0","0,0","1414,8887671232876","0,0",NaN,NaN,"12,0","0,0","0,0","0,0","94290,0","0,0","0,0",NaN,NaN,NaN,3.0,NaN,NaN,"0,0","0,0","0,0","795,0","7741,0",NaN,NaN,4.0,0.0,1.0,NaN,"192,0",NaN,NaN,0.0,"170,0",1446.0,NaN,"350000,0",1000000.0,NaN,"522,0",6.0,"0,061224489795918366",0.0,"1,0","0,4545","0,0","0,0",1446.0,NaN,NaN,"0,0","139554,0","24,05",NaN,NaN,NaN,"0,0","84,0",0.0,"690038,0","0,0","9,0",NaN,"0,5523135540134384",NaN

In [6]:
data_test.info(verbose='True', show_counts='True')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73214 entries, 0 to 73213
Data columns (total 222 columns):
 #    Column                                                                                           Non-Null Count  Dtype
---   ------                                                                                           --------------  -----
 0    id                                                                                               73214 non-null  int64
 1    dt                                                                                               73214 non-null  object
 2    turn_cur_cr_avg_act_v2                                                                           57244 non-null  object
 3    salary_6to12m_avg                                                                                7634 non-null   object
 4    hdb_bki_total_max_limit                                                                          62809 non-null  float64
 5    dp_ils_paymentssum_avg_12m                                                                       19946 non-null  object
 6    hdb_bki_total_cc_max_limit                                                                       57863 non-null  float64
 7    incomeValue                                                                                      58031 non-null  object
 8    gender                                                                                           73214 non-null  object
 9    avg_cur_cr_turn                                                                                  58159 non-null  object
 10   adminarea                                                                                        55584 non-null  object
 11   turn_cur_cr_avg_v2                                                                               57517 non-null  object
 12   turn_cur_cr_max_v2                                                                               57517 non-null  object
 13   hdb_bki_total_pil_max_limit                                                                      55642 non-null  float64
 14   age                                                                                              73214 non-null  object
 15   dp_ils_avg_salary_1y                                                                             19419 non-null  object
 16   turn_cur_cr_sum_v2                                                                               57517 non-null  object
 17   by_category__amount__sum__eoperation_type_name__ishodjaschij_bystryj_platezh_sbp                 45121 non-null  object
 18   turn_cur_db_sum_v2                                                                               57517 non-null  object
 19   turn_cur_db_avg_act_v2                                                                           56693 non-null  object
 20   dp_ils_avg_salary_2y                                                                             19718 non-null  object
 21   curr_rur_amt_cm_avg                                                                              57294 non-null  object
 22   turn_cur_db_avg_v2                                                                               57517 non-null  object
 23   by_category__amount__sum__eoperation_type_name__vhodjaschij_bystryj_platezh_sbp                  41957 non-null  object
 24   dp_ils_paymentssum_avg_6m                                                                        19946 non-null  object
 25   avg_cur_db_turn                                                                                  58159 non-null  object
 26   hdb_bki_active_cc_max_limit                                                                      51466 non-null  float64
 27   incomeValueCategory                                                                              58031 non-null  object
 28   avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate               40070 non-null  object
 29   avg_credit_turn_rur                                                                              58159 non-null  object
 30   dp_ils_salary_ratio_1y3y                                                                         19249 non-null  object
 31   by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona                       35036 non-null  object
 32   turn_cur_cr_7avg_avg_v2                                                                          57517 non-null  object
 33   dp_ils_accpayment_avg_12m                                                                        19946 non-null  object
 34   curbal_usd_amt_cm_avg                                                                            72632 non-null  object
 35   avg_by_category__amount__sum__cashflowcategory_name__supermarkety                                46343 non-null  object
 36   avg_loan_cnt_with_insurance                                                                      15669 non-null  object
 37   avg_by_category__amount__sum__cashflowcategory_name__gipermarkety                                43828 non-null  object
 38   city_smart_name                                                                                  63498 non-null  object
 39   uniV5                                                                                            58031 non-null  object
 40   turn_cur_db_max_v2                                                                               57517 non-null  object
 41   avg_by_category__amount__sum__cashflowcategory_name__kafe                                        45565 non-null  object
 42   turn_other_db_max_v2                                                                             43254 non-null  object
 43   turn_cur_cr_min_v2                                                                               57517 non-null  object
 44   hdb_bki_other_active_pil_outstanding                                                             30356 non-null  float64
 45   dp_ewb_last_employment_position                                                                  18291 non-null  object
 46   turn_cur_db_min_v2                                                                               57517 non-null  object
 47   hdb_bki_total_products                                                                           66724 non-null  float64
 48   per_capita_income_rur_amt                                                                        66256 non-null  object
 49   avg_debet_turn_rur                                                                               58159 non-null  object
 50   hdb_relend_active_max_psk                                                                        62621 non-null  object
 51   dda_rur_amt_curr_v2                                                                              70163 non-null  object
 52   mob_cnt_days                                                                                     52575 non-null  object
 53   dp_ils_days_from_last_doc                                                                        19946 non-null  object
 54   avg_6m_money_transactions                                                                        52577 non-null  object
 55   transaction_category_supermarket_percent_cnt_2m                                                  41397 non-null  object
 56   pil                                                                                              69874 non-null  object
 57   hdb_bki_total_max_overdue_sum                                                                    62490 non-null  float64
 58   avg_6m_clothing                                                                                  52577 non-null  object
 59   avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi                           37257 non-null  object
 60   addrref                                                                                          65071 non-null  object
 61   bki_total_auto_cnt                                                                               60800 non-null  float64
 62   dp_payoutincomedata_payout_avg_3_month                                                           15375 non-null  object
 63   hdb_outstand_sum                                                                                 62791 non-null  object
 64   avg_3m_money_transactions                                                                        52577 non-null  object
 65   dp_address_unique_regions                                                                        18437 non-null  object
 66   min_balance_rur_amt_6m_af                                                                        11990 non-null  object
 67   transaction_category_supermarket_sum_cnt_m3_4                                                    40349 non-null  object
 68   dp_payoutincomedata_payout_max_3_month                                                           15375 non-null  object
 69   hdb_bki_total_ip_max_limit                                                                       19515 non-null  float64
 70   hdb_bki_total_cnt                                                                                66661 non-null  float64
 71   blacklist_flag                                                                                   72632 non-null  object
 72   bki_total_oth_cnt                                                                                60800 non-null  float64
 73   dp_payoutincomedata_payout_sum_3_month                                                           15375 non-null  object
 74   hdb_relend_outstand_sum                                                                          62796 non-null  object
 75   total_rur_amt_cm_avg                                                                             57294 non-null  object
 76   mob_cover_days                                                                                   52575 non-null  object
 77   dp_payoutincomedata_payout_max_6_month                                                           15375 non-null  object
 78   label_Below_50k_share_r1                                                                         33655 non-null  object
 79   turn_fdep_db_sum_v2                                                                              5000 non-null   object
 80   dp_ils_accpayment_avg_6m_current                                                                 19946 non-null  object
 81   transaction_category_cash_percent_amt_2m                                                         23892 non-null  object
 82   curr_rur_amt_3m_avg                                                                              67389 non-null  object
 83   transaction_category_restaurants_sum_amt_m2                                                      21222 non-null  object
 84   loan_cnt                                                                                         15669 non-null  object
 85   turn_fdep_db_avg_v2                                                                              5000 non-null   object
 86   turn_cur_db_7avg_avg_v2                                                                          57517 non-null  object
 87   bki_total_ip_max_outstand                                                                        14978 non-null  float64
 88   amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate  27456 non-null  object
 89   profit_income_out_rur_amt_12m                                                                    72725 non-null  object
 90   avg_6m_hotels                                                                                    52577 non-null  object
 91   hdb_ovrd_sum                                                                                     62801 non-null  object
 92   dp_ils_total_seniority                                                                           20308 non-null  object
 93   dp_ils_paymentssum_avg_6m_current                                                                19946 non-null  object
 94   smsInWavg6m                                                                                      47318 non-null  object
 95   avg_fdep_db_turn                                                                                 58159 non-null  object
 96   device_iphone_avg                                                                                52575 non-null  object
 97   by_category__amount__sum__eoperation_type_name__platezh_za_mobilnyj_cherez_ps                    34302 non-null  object
 98   avg_balance_rur_amt_1m_af                                                                        11990 non-null  object
 99   curr_rur_amt_cm_avg_period_days_ago_v2                                                           70163 non-null  object
 100  avg_by_category__amount__sum__cashflowcategory_name__oteli                                       8733 non-null   object
 101  hdb_bki_total_ip_cnt                                                                             62809 non-null  float64
 102  hdb_bki_active_cc_max_outstand                                                                   51394 non-null  float64
 103  hdb_other_outstand_sum                                                                           55295 non-null  object
 104  days_to_last_transaction                                                                         63284 non-null  object
 105  hdb_bki_total_pil_max_overdue                                                                    54410 non-null  float64
 106  vert_pil_last_credit_step_screen_view_3m                                                         54677 non-null  object
 107  acard                                                                                            69874 non-null  object
 108  bki_total_il_max_limit                                                                           41609 non-null  float64
 109  other_credits_count                                                                              69275 non-null  object
 110  tz_msk_timedelta                                                                                 55584 non-null  object
 111  turn_save_db_min_v2                                                                              17062 non-null  object
 112  profit_income_out_rur_amt_9m                                                                     72725 non-null  object
 113  dp_ils_ipkcurrentyear_currentyearpensfactor                                                      18285 non-null  object
 114  avg_by_category__amount__sum__cashflowcategory_name__odezhda                                     34442 non-null  object
 115  cntOnnRinCallAvg6m                                                                               10714 non-null  object
 116  dda_rur_amt_3m_avg                                                                               67389 non-null  object
 117  winback_cnt                                                                                      72632 non-null  object
 118  salary_median_in_gex_r1                                                                          33655 non-null  object
 119  dp_payoutincomedata_payout_avg_prev_year                                                         13471 non-null  object
 120  avg_amount_daily_transactions_90d                                                                49575 non-null  object
 121  vert_has_app_ru_tinkoff_investing                                                                54677 non-null  object
 122  transaction_category_supermarket_inc_cnt_2m                                                      41397 non-null  object
 123  vert_pil_sms_success_3m                                                                          54677 non-null  object
 124  min_balance_rur_amt_1m_af                                                                        11990 non-null  object
 125  dp_ils_max_seniority                                                                             20044 non-null  object
 126  avg_by_category__amount__sum__cashflowcategory_name__set_supermarketov                           9483 non-null   object
 127  label_500k_to_1M_share_r1                                                                        33655 non-null  object
 128  avg_by_category__amount__sum__cashflowcategory_name__zarubezhnye_finansovye_operatsii            3431 non-null   object
 129  bki_total_products                                                                               60800 non-null  float64
 130  avg_6m_all                                                                                       52577 non-null  object
 131  dp_ils_avg_simultanious_jobs_5y                                                                  19906 non-null  object
 132  dp_ewb_dismissal_due_contract_violation_by_lb_cnt                                                19800 non-null  object
 133  summarur_1m_purch                                                                                52577 non-null  object
 134  diff_avg_cr_db_turn                                                                              58159 non-null  object
 135  dp_ils_cnt_changes_1y                                                                            20044 non-null  object
 136  dp_ils_employeers_cnt_last_month                                                                 19946 non-null  object
 137  dp_payoutincomedata_payout_avg_6_month                                                           15375 non-null  object
 138  dp_ewb_last_organization                                                                         15070 non-null  float64
 139  by_category__amount__sum__eoperation_type_name__perevod_mezhdu_svoimi_schetami                   34106 non-null  object
 140  bki_active_auto_cnt                                                                              60800 non-null  float64
 141  turn_other_cr_avg_act_v2                                                                         42681 non-null  object
 142  cntVoiceOutMob6m                                                                                 47318 non-null  object
 143  avg_by_category__amount__sum__cashflowcategory_name__puteshestvija                               10534 non-null  object
 144  loanacc_rur_amt_cm_avg                                                                           57294 non-null  object
 145  transaction_category_supermarket_sum_cnt_m2                                                      41397 non-null  object
 146  transaction_category_supermarket_sum_amt_d15                                                     34417 non-null  object
 147  avg_fdep_cr_turn                                                                                 58159 non-null  object
 148  transaction_category_restaurants_percent_cnt_2m                                                  21222 non-null  object
 149  bki_total_max_limit                                                                              54247 non-null  float64
 150  avg_by_category__amount__sum__cashflowcategory_name__reklama_v_internete                         4422 non-null   object
 151  transaction_category_restaurants_percent_amt_2m                                                  21222 non-null  object
 152  turn_fdep_db_avg_act_v2                                                                          3587 non-null   object
 153  dp_ils_accpayment_avg_6m                                                                         19946 non-null  object
 154  turn_other_cr_sum_v2                                                                             43254 non-null  object

In [7]:
data_test.head(5)

,id,dt,turn_cur_cr_avg_act_v2,salary_6to12m_avg,hdb_bki_total_max_limit,dp_ils_paymentssum_avg_12m,hdb_bki_total_cc_max_limit,incomeValue,gender,avg_cur_cr_turn,adminarea,turn_cur_cr_avg_v2,turn_cur_cr_max_v2,hdb_bki_total_pil_max_limit,age,dp_ils_avg_salary_1y,turn_cur_cr_sum_v2,by_category__amount__sum__eoperation_type_name__ishodjaschij_bystryj_platezh_sbp,turn_cur_db_sum_v2,turn_cur_db_avg_act_v2,dp_ils_avg_salary_2y,curr_rur_amt_cm_avg,turn_cur_db_avg_v2,by_category__amount__sum__eoperation_type_name__vhodjaschij_bystryj_platezh_sbp,dp_ils_paymentssum_avg_6m,avg_cur_db_turn,hdb_bki_active_cc_max_limit,incomeValueCategory,avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate,avg_credit_turn_rur,dp_ils_salary_ratio_1y3y,by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona,turn_cur_cr_7avg_avg_v2,dp_ils_accpayment_avg_12m,curbal_usd_amt_cm_avg,avg_by_category__amount__sum__cashflowcategory_name__supermarkety,avg_loan_cnt_with_insurance,avg_by_category__amount__sum__cashflowcategory_name__gipermarkety,city_smart_name,uniV5,turn_cur_db_max_v2,avg_by_category__amount__sum__cashflowcategory_name__kafe,turn_other_db_max_v2,turn_cur_cr_min_v2,hdb_bki_other_active_pil_outstanding,dp_ewb_last_employment_position,turn_cur_db_min_v2,hdb_bki_total_products,per_capita_income_rur_amt,avg_debet_turn_rur,hdb_relend_active_max_psk,dda_rur_amt_curr_v2,mob_cnt_days,dp_ils_days_from_last_doc,avg_6m_money_transactions,transaction_category_supermarket_percent_cnt_2m,pil,hdb_bki_total_max_overdue_sum,avg_6m_clothing,avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi,addrref,bki_total_auto_cnt,dp_payoutincomedata_payout_avg_3_month,hdb_outstand_sum,avg_3m_money_transactions,dp_address_unique_regions,min_balance_rur_amt_6m_af,transaction_category_supermarket_sum_cnt_m3_4,dp_payoutincomedata_payout_max_3_month,hdb_bki_total_ip_max_limit,hdb_bki_total_cnt,blacklist_flag,bki_total_oth_cnt,dp_payoutincomedata_payout_sum_3_month,hdb_relend_outstand_sum,total_rur_amt_cm_avg,mob_cover_days,dp_payoutincomedata_payout_max_6_month,label_Below_50k_share_r1,turn_fdep_db_sum_v2,dp_ils_accpayment_avg_6m_current,transaction_category_cash_percent_amt_2m,curr_rur_amt_3m_avg,transaction_category_restaurants_sum_amt_m2,loan_cnt,turn_fdep_db_avg_v2,turn_cur_db_7avg_avg_v2,bki_total_ip_max_outstand,amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate,profit_income_out_rur_amt_12m,avg_6m_hotels,hdb_ovrd_sum,dp_ils_total_seniority,dp_ils_paymentssum_avg_6m_current,smsInWavg6m,avg_fdep_db_turn,device_iphone_avg,by_category__amount__sum__eoperation_type_name__platezh_za_mobilnyj_cherez_ps,avg_balance_rur_amt_1m_af,curr_rur_amt_cm_avg_period_days_ago_v2,avg_by_category__amount__sum__cashflowcategory_name__oteli,hdb_bki_total_ip_cnt,hdb_bki_active_cc_max_outstand,hdb_other_outstand_sum,days_to_last_transaction,hdb_bki_total_pil_max_overdue,vert_pil_last_credit_step_screen_view_3m,acard,bki_total_il_max_limit,other_credits_count,tz_msk_timedelta,turn_save_db_min_v2,profit_income_out_rur_amt_9m,dp_ils_ipkcurrentyear_currentyearpensfactor,avg_by_category__amount__sum__cashflowcategory_name__odezhda,cntOnnRinCallAvg6m,dda_rur_amt_3m_avg,winback_cnt,salary_median_in_gex_r1,dp_payoutincomedata_payout_avg_prev_year,avg_amount_daily_transactions_90d,vert_has_app_ru_tinkoff_investing,transaction_category_supermarket_inc_cnt_2m,vert_pil_sms_success_3m,min_balance_rur_amt_1m_af,dp_ils_max_seniority,avg_by_category__amount__sum__cashflowcategory_name__set_supermarketov,label_500k_to_1M_share_r1,avg_by_category__amount__sum__cashflowcategory_name__zarubezhnye_finansovye_operatsii,bki_total_products,avg_6m_all,dp_ils_avg_simultanious_jobs_5y,dp_ewb_dismissal_due_contract_violation_by_lb_cnt,summarur_1m_purch,diff_avg_cr_db_turn,dp_ils_cnt_changes_1y,dp_ils_employeers_cnt_last_month,dp_payoutincomedata_payout_avg_6_month,dp_ewb_last_organization,by_category__amount__sum__eoperation_type_name__perevod_mezhdu_svoimi_schetami,bki_active_auto_cnt,turn_other_cr_avg_act_v2,cntVoiceOutMob6m,avg_by_category__amount__sum__cashflowcategory_name__puteshestvija,loanacc_rur_amt_cm_avg,transaction_category_supermarket_sum_cnt_m2,transaction_category_supermarket_sum_amt_d15,avg_fdep_cr_turn,transaction_category_restaurants_percent_cnt_2m,bki_total_max_limit,avg_by_category__amount__sum__cashflowcategory_name__reklama_v_internete,transaction_category_restaurants_percent_amt_2m,turn_fdep_db_avg_act_v2,dp_ils_accpayment_avg_6m,turn_other_cr_sum_v2,client_active_flag,avg_by_category__amount__sum__cashflowcategory_name__produkty,curr_rur_amt_cm_avg_inc_v2,nonresident_flag,avg_by_category__amount__sum__cashflowcategory_name__kosmetika,vert_has_app_ru_vtb_invest,dp_ils_avg_salary_3y,hdb_bki_total_auto_max_limit,days_after_last_request,cntRegionTripsWavg1m,vert_has_app_ru_cian_main,loanacc_rur_amt_curr_v2,avg_3m_no_cat,vert_ghost_close_dpay3_last_days,vert_has_app_ru_raiffeisennews,dp_ils_days_ip_share_5y,avg_by_category__amount__sum__cashflowcategory_name__platezhi_cherez_internet,hdb_bki_total_micro_max_overdue,bki_total_active_products,by_category__amount__sum__eoperation_type_name__perevod_s_karty_na_kartu,calledCtnOutGroup,vert_pil_loan_application_success_3m,vert_pil_fee_discount_change_3m,businessTelSubs,profit_income_out_rur_amt_l2m,avg_3m_healthcare_services,dp_ils_paymentssum_month_avg,ovrd_sum,hdb_bki_total_active_products,hdb_bki_total_micro_cnt,hdb_bki_active_pil_cnt,loan_cur_amt,mob_total_sessions,period_last_act_ad,dp_ils_days_multiple_job_share_2y,hdb_bki_total_cc_max_overdue,lifetimeComp,hdb_bki_total_pil_last_days,amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__elektronnye_dengi,turn_save_cr_max_v2,hdb_bki_active_pil_max_limit,dp_ils_accpayment_avg_3m,avg_6m_restaurants,hdb_bki_total_pil_cnt,transaction_category_fastfood_percent_cnt_2m,hdb_bki_total_pil_max_del90,accountsalary_out_flag,cntBlockWavg6m,express_rur_amt_cm_avg,loanacc_rur_amt_cm_avg_inc_v2,hdb_bki_last_product_days,dp_ils_days_multiple_job_cnt_5y,dp_ils_accpayment_month_avg,cred_dda_rur_amt_3m_avg,avg_3m_all,hdb_other_active_max_psk,hdb_bki_other_active_ip_outstanding,total_sum,dp_ils_uniq_companies_1y,avg_6m_travel,avg_6m_government_services,hdb_bki_active_cc_max_overdue,total_rur_amt_cm_avg_period_days_ago_v2,label_Above_1M_share_r1,transaction_category_supermarket_sum_cnt_d15,max_balance_rur_amt_1m_af,first_salary_income
0,0,2024-08-31,"805319,38",NaN,61137.47,NaN,60000.0,"159999,0",Женский,"69740,0",Удмуртская Республика,"67109,94833333333","70005,0",61137.47,"59,0",NaN,"805319,38","3538,356164383562","845759,3299999998","845759,3299999998",NaN,"88972,0","70479,94416666665",NaN,NaN,"61405,0",NaN,"7,0",NaN,"69740,0",NaN,"4643,835616438357","40002,0",NaN,"0,0","1300,990684931507",NaN,"2611,537808219178",Ижевск,"0,0244413","100000,0","986,2191780821918",NaN,"805319,38",NaN,NaN,"845759,3299999998",6.0,"36013,0","61405,0","0,0","82037,0","25,0",NaN,"0,0","0,6578947368421053","0,0",2395.00,"840,0",NaN,Удмуртская Республика,0.0,NaN,"0,0","0,0",NaN,NaN,"14,0",NaN,NaN,36.0,"0,0",0.0,NaN,"0,0","88972,0","0,2777777777777778",NaN,"0,30303030303030304",NaN,NaN,NaN,"59660,0",NaN,NaN,NaN,"210,0",NaN,NaN,"555,1666666666666","0,0","0,0",NaN,NaN,"82,0938","0,0","0,0",NaN,NaN,"80228,0",NaN,0.0,NaN,NaN,"7,0",2352.79,"0,0","0,0",61137.47,"0,0","1,0",NaN,"564,2222222222222",NaN,"3842,834794520548",NaN,"59660,0","0,0","73690,36751269035",NaN,"643,6572222222223","0,0","1,2166666666666666","0,0",NaN,NaN,NaN,"0,06060606060606061",NaN,2.0,"14429,0",NaN,NaN,"210,0","8334,660000000018",NaN,NaN,NaN,NaN,NaN,0.0,NaN,"204,5167",NaN,"0,0","25,0","210,0","0,0",NaN,61137.47,NaN,NaN,NaN,NaN,NaN,"1,0","4171,100547945206","-2999,0","0,0","924,0","0,0",NaN,NaN,"43,0","6,1788","0,0","0,0","0,0","0,0","0,0",NaN,NaN,NaN,0.0,NaN,NaN,"0,0","0,0","0,0","467,0","4177,0",NaN,NaN,0.0,0.0,0.0,NaN,"65,0",NaN,NaN,0.0,"116,0",1364.0,NaN,NaN,NaN,NaN,"844,0",5.0,NaN,0.0,"1,0","0,0044","0,0","0,0",1364.0,NaN,NaN,"0,0","19310,0","0,0",NaN,NaN,NaN,"0,0","0,0",NaN,"80228,0","0,0","1,0",NaN,NaN
1,1,2024-10-31,"306240,0",NaN,949500.00,NaN,230000.0,"108834,0",Мужской,"63513,0",Саратовская область,"25520,0","40000,0",949500.00,"46,0",NaN,"306240,0","1619,178082191781","293559,04","293559,04",NaN,"3375,0","24463,25333333333","2301,3698630136987",NaN,"60123,0",230000.0,"6,0",NaN,"88566,0",NaN,"986,3013698630137","25246,666666666668",NaN,"122,0","155,98191780821918","1,0","389,61041095890414",Саратов,"0,0142499","50000,0","814,8821917808219","19843,14","306240,0",NaN,NaN,"293559,04",5.0,"35665,0","73537,0","61,594","16349,0","41,0",NaN,"0,0",NaN,"0,0",0.00,"199,0",NaN,Саратовская область,0.0,NaN,"89951,44140625","0,0",NaN,NaN,"9,0",NaN,NaN,23.0,"0,0",0.0,NaN,"89951,44140625","29630,0","0,45555555555555555",NaN,"0,6666666666666666",NaN,NaN,NaN,"10960,0",NaN,"1,0",NaN,"14029,6",NaN,NaN,"103,0","0,0","0,0",NaN,NaN,"155,727","0,0","0,9662921348314607",NaN,NaN,"10778,0",NaN,0.0,50000.00,"50000,0","2,0",0.00,"0,0","0,0",949500.00,"1,0","1,0","58500,0","101,44444444444444",NaN,"100,68493150684932",NaN,"25122,0","1,0","42850,98483606557",NaN,"396,8222222222222","0,0",NaN,"0,0",NaN,NaN,NaN,"0,0",NaN,2.0,"11871,0",NaN,NaN,"13112,0","15029,846666666679",NaN,NaN,NaN,NaN,"5120,54794520548",0.0,"32846,98","392,2",NaN,"0,0",NaN,NaN,"0,0",NaN,949500.00,NaN,NaN,NaN,NaN,"98540,94","1,0","375,8605479452055","-3,0","0,0",NaN,"0,0",NaN,NaN,"8,0","0,6489","0,0","0,0","0,0","0,0","0,0",NaN,NaN,NaN,1.0,NaN,NaN,"0,0","0,0","0,0","276,0","0,0",NaN,"0,0",3.0,0.0,0.0,NaN,"89,0",NaN,NaN,0.0,"176,0",553.0,NaN,"20000,0",NaN,NaN,"0,0",2.0,NaN,0.0,"1,0","0,0186","0,0","0,0",201.0,NaN,NaN,"0,0","11868,0","25,356",NaN,"0,0",NaN,"0,0","0,0",0.0,"24888,0","0,0",NaN,NaN,NaN
2,3,2024-09-30,"164908,72999999998",NaN,178000.00,NaN,178000.0,"59203,0",Женский,"132,0",Воронежская область,"27484,78833333333","26924,12",101500.00,"22,0",NaN,"329817,45999999996","13312,849315068494","330233,76","165116,88",NaN,"590,0","27519,48","5452,602739726028",NaN,"149,0",178000.0,"3,0",NaN,"132,0",NaN,"624,6575342465753","0,0",NaN,"10,0",NaN,"1,0",NaN,Москва,"0,1290661","26924,0",NaN,"45000,0","71206,8",NaN,NaN,"71206,8",26.0,"49227,0","10339,0","27,412","0,0",NaN,NaN,"0,0",NaN,"0,0",7900.00,"0,0","5,778082191780822",г. Москва,0.0,NaN,"258175,43359375","0,0",NaN,NaN,NaN,NaN,NaN,124.0,"0,0",0.0,NaN,"237055,43359375","596,0",NaN,NaN,NaN,NaN,NaN,NaN,"289,0",NaN,"1,0",NaN,"0,0",NaN,NaN,"4003,6666666666665","0,0","0,0",NaN,NaN,"105,2899","0,0",NaN,NaN,NaN,"223,0",NaN,0.0,132999.52,"237055,43359375","60,0",6693.00,"0,0","0,0",101500.00,"4,0","0,0",NaN,"4036,6666666666665",NaN,NaN,NaN,"311,0","0,0",NaN,NaN,"0,7811111111111111","0,0",NaN,"0,0",NaN,NaN,NaN,NaN,NaN,4.0,"683,0",NaN,NaN,"0,0","-10206,446666666667",NaN,NaN,NaN,NaN,"6430,602739726028",0.0,"31783,398999999994","206779,713",NaN,"30208,0",NaN,NaN,"0,0",NaN,133000.00,"18,08219178082192",NaN,NaN,NaN,"317833,98999999993","0,0",NaN,"-223,0","0,0",NaN,"0,0",NaN,NaN,"23,0","45,7391","0,0","0,0","0,0","0,0","0,0",NaN,NaN,0.00,1.0,NaN,NaN,"0,0","0,0","0,0","3344,0","0,0",NaN,"0,0",7.0,16.0,0.0,NaN,NaN,NaN,NaN,7900.0,"66,0",182.0,"70,3",NaN,NaN,NaN,"0,0",3.0,NaN,0.0,"1,0","0,058","0,0","0,0",122.0,NaN,NaN,"0,0","23,0","27,412",NaN,"38630,630000000005",NaN,"0,0","0,0",2363.9,"223,0",NaN,NaN,NaN,NaN
3,9,2024-10-31,"2374846,42",NaN,25500.00,"126247,44835851202",4999.0,"180906,0",Женский,"290339,0",Алтайский край,"197903,86833333332","108802,85",20000.00,"36,0","88900,02201557094","2374846,42","11772,0","2375671,969999999","2375671,969999999","56955,06864445668","21940,0","197972,66416666657","21914,87671232877","147169,61669832104","297461,0",NaN,"7,0","36462,433150684934","290772,0","1,703849135952116","5531,506849315068","6591,415","20224,838952843627","197,0","7748,846301369864",NaN,"12095,878356164385",Барнаул,"0,1163881","82856,22","7293,423287671234","1000,0","2374846,42",7000.0,Менеджер ВЭД,"2375671,969999999",60.0,"39473,0","297794,0","292,8","2019,0","70,0","275,0","59795,0","0,3728813559322034","0,0",6400.46,"8895,0","74700,72575342466",Алтайский край,0.0,"50454,04666666667","384029,390625","64431,0",22,"1000,0","96,0","115000,0",NaN,121.0,"0,0",0.0,"151362,14","364341,390625","21940,0","0,7777777777777778","125060,85","0,7",NaN,"23576,57120518712","0,4378192660178915","24562,0","874,0",NaN,NaN,"2533,6583333333333",NaN,"168000,0","492,1666666666667","0,0","15064,7001953125","8,03833","147169,61669832104","152,3184","0,0","0,0","283,56164383561645","0,0","25734,0",NaN,0.0,NaN,"384029,390625","5,0",6400.46,"0,0","0,0",NaN,"24,0","4,0",NaN,"638,0","2,187","5391,123287671233",NaN,"24562,0","0,0","37175,20959879206","42529,974","11408,575777777782","0,0","0,9104308390022676","0,0","0,0","5840,0",NaN,"0,0",NaN,1.0,"324763,0","0,603348729792","0,0","111628,0","-7022,2733333333745","3,0","1,0","77353,94833333333",2.221223e+09,NaN,0.0,"452,6666666666667","211,55","394,5205479452055","0,0","66,0","3194,74","0,0","0,01694915254237288",19490.00,"28,767123287671236","0,0026573197118030362",NaN,"23576,57120518712","1358,0","1,0","9633,733150684931","-10529,0","0,0","2268,7717808219177","0,0","52175,99383638701",NaN,"41,0","31,731","0,0","0,0","140245,0","0,0","0,0","0,0",NaN,4102.45,1.0,NaN,NaN,"0,0","0,0","0,0","930,0","1835,0","75683,71916707885",NaN,33.0,54.0,3.0,"100000,0","351,0",1677-09-01,"0,009419152276295133",5426.0,"53,0",39.0,"279892,0",NaN,19752.58,"20452,765497495457","7642,0",6.0,"0,22598870056497175",74.0,"1,0","0,0552","0,0","0,0",38.0,"6,0","11733,891398067552","0,0","339302,0","292,8",NaN,NaN,"3,0","800,0","0,0",NaN,"25734,0","0,0","7,0","0,0",NaN
4,11,2024-11-30,"735902,71","47828,145620567375",60000.00,NaN,60000.0,"24922,0",Мужской,"76924,0",Саратовская область,"61325,22583333333","70608,0",7000.00,"20,0",NaN,"735902,71","17070,97315068493","734237,9000000001","734237,9000000001",NaN,"1160,0","61186,491666666676","426,46684931506854",NaN,"79181,0",15000.0,"2,0","410,95890410958907","141681,0",NaN,"770,5479452054794","8902,792857142858",NaN,"12,0","455,60465753424654",NaN,"562,3750684931506",Москва,"0,0464274","70468,09","963,8531506849316","60000,0","735902,71",NaN,NaN,"734237,9000000001",4.0,"35665,0","123389,0","60,021","5652,0","71,0",NaN,"857,0","0,5698924731182796","0,0",0.00,"0,0","1237,934794520548",г. Москва,0.0,NaN,"21999,2998046875","0,0",NaN,NaN,"69,0",NaN,NaN,16.0,"0,0",0.0,NaN,"21999,2998046875","1169,0","0,7888888888888889",NaN,"1,0",NaN,NaN,NaN,"2800,0",NaN,NaN,NaN,"8664,942857142856",NaN,NaN,"893,4166666666666","250,0","0,0",NaN,NaN,"245,5556","0,0","0,9044368600682594","12,328767123287673",NaN,"1150,0","123,28767123287672",0.0,14999.30,"14999,2998046875","1,0",0.00,"0,0","1,0",NaN,"1,0","1,0",NaN,"1236,888888888889",NaN,NaN,NaN,"2832,0","0,0","31215,62274064734",NaN,"482,0343333333333","0,0","1,1273310023310024","0,0",NaN,NaN,NaN,"0,0",NaN,2.0,"16785,0",NaN,NaN,"19154,0","18292,380000000005",NaN,NaN,NaN,NaN,"667,0208219178082",0.0,"34877,27833333333","868,8667",NaN,"0,0","53,0","6117,47","0,0",NaN,60000.00,NaN,NaN,NaN,NaN,"209263,66999999998","1,0","3045,837534246576","786,0","0,0",NaN,"0,0",NaN,NaN,"5,0","6,8682","0,0","0,0","1471,0","0,0","0,0",NaN,NaN,NaN,1.0,NaN,NaN,"0,0","0,0","0,0","2265,0","1159,0",NaN,"0,0",2.0,0.0,0.0,NaN,"293,0",NaN,NaN,0.0,"51,0",351.0,"10412,63",NaN,NaN,NaN,"1297,0",0.0,"0,07526881720430108",NaN,"1,0","0,0969","0,0","0,0",159.0,NaN,NaN,"0,0","14026,0","24,476",NaN,"0,0",NaN,"0,0","0,0",0.0,"1214,0","0,0","15,0",NaN,NaN

In [8]:
print("Cтолбцы для удаления (>50%):")
columns_to_drop = analyze_missing_columns(data_train,
                                          threshold=0.5,
                                          sort_alphabetical=True)

Cтолбцы для удаления (>50%):
Столбцы с пропусками > 50%:
amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__elektronnye_dengi: 67.3% (51642 пропусков)
amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate: 62.0% (47645 пропусков)
avg_balance_rur_amt_1m_af: 85.5% (65653 пропусков)
avg_by_category__amount__sum__cashflowcategory_name__kosmetika: 62.0% (47632 пропусков)
avg_by_category__amount__sum__cashflowcategory_name__odezhda: 54.2% (41616 пропусков)
avg_by_category__amount__sum__cashflowcategory_name__oteli: 88.5% (67925 пропусков)
avg_by_category__amount__sum__cashflowcategory_name__platezhi_cherez_internet: 98.4% (75589 пропусков)
avg_by_category__amount__sum__cashflowcategory_name__puteshestvija: 86.6% (66512 пропусков)
avg_by_category__amount__sum__cashflowcategory_name__reklama_v_internete: 93.2% (71564 пропусков)
avg_by_category__amount__sum__cashflowcategory_name__set_supermarketov: 87.5% (67217 пропусков)
avg_by_category__amount__sum__cashflowcategory_name__zarubezhnye_finansovye_operatsii: 92.7% (71218 пропусков)
avg_loan_cnt_with_insurance: 75.0% (57584 пропусков)
bki_total_ip_max_outstand: 81.2% (62329 пропусков)
by_category__amount__sum__eoperation_type_name__ishodjaschij_bystryj_platezh_sbp: 58.7% (45042 пропусков)
by_category__amount__sum__eoperation_type_name__perevod_mezhdu_svoimi_schetami: 66.7% (51253 пропусков)
by_category__amount__sum__eoperation_type_name__perevod_s_karty_na_kartu: 88.2% (67700 пропусков)
by_category__amount__sum__eoperation_type_name__platezh_za_mobilnyj_cherez_ps: 68.1% (52256 пропусков)
by_category__amount__sum__eoperation_type_name__vhodjaschij_bystryj_platezh_sbp: 61.0% (46852 пропусков)
calledCtnOutGroup: 84.6% (64932 пропусков)
cntOnnRinCallAvg6m: 84.5% (64921 пропусков)
dp_address_unique_regions: 80.5% (61814 пропусков)
dp_ewb_dismissal_due_contract_violation_by_lb_cnt: 78.9% (60577 пропусков)
dp_ewb_last_employment_position: 80.4% (61705 пропусков)
dp_ewb_last_organization: 83.2% (63893 пропусков)
dp_ils_accpayment_avg_12m: 78.5% (60283 пропусков)
dp_ils_accpayment_avg_3m: 78.5% (60283 пропусков)
dp_ils_accpayment_avg_6m: 78.5% (60283 пропусков)
dp_ils_accpayment_avg_6m_current: 78.5% (60283 пропусков)
dp_ils_accpayment_month_avg: 78.5% (60283 пропусков)
dp_ils_avg_salary_1y: 79.3% (60860 пропусков)
dp_ils_avg_salary_2y: 78.8% (60484 пропусков)
dp_ils_avg_salary_3y: 78.6% (60387 пропусков)
dp_ils_avg_simultanious_jobs_5y: 78.5% (60308 пропусков)
dp_ils_cnt_changes_1y: 78.4% (60198 пропусков)
dp_ils_days_from_last_doc: 78.5% (60283 пропусков)
dp_ils_days_ip_share_5y: 78.5% (60308 пропусков)
dp_ils_days_multiple_job_cnt_5y: 78.5% (60308 пропусков)
dp_ils_days_multiple_job_share_2y: 78.8% (60483 пропусков)
dp_ils_employeers_cnt_last_month: 78.5% (60283 пропусков)
dp_ils_ipkcurrentyear_currentyearpensfactor: 82.5% (63354 пропусков)
dp_ils_max_seniority: 78.4% (60198 пропусков)
dp_ils_paymentssum_avg_12m: 78.5% (60283 пропусков)
dp_ils_paymentssum_avg_6m: 78.5% (60283 пропусков)
dp_ils_paymentssum_avg_6m_current: 78.5% (60283 пропусков)
dp_ils_paymentssum_month_avg: 78.5% (60283 пропусков)
dp_ils_salary_ratio_1y3y: 79.4% (60944 пропусков)
dp_ils_total_seniority: 78.3% (60103 пропусков)
dp_ils_uniq_companies_1y: 78.4% (60197 пропусков)
dp_payoutincomedata_payout_avg_3_month: 85.8% (65855 пропусков)
dp_payoutincomedata_payout_avg_6_month: 85.8% (65855 пропусков)
dp_payoutincomedata_payout_avg_prev_year: 89.7% (68915 пропусков)
dp_payoutincomedata_payout_max_3_month: 85.8% (65855 пропусков)
dp_payoutincomedata_payout_max_6_month: 85.8% (65855 пропусков)
dp_payoutincomedata_payout_sum_3_month: 85.8% (65855 пропусков)
first_salary_income: 88.7% (68118 пропусков)
hdb_bki_other_active_ip_outstanding: 81.2% (62367 пропусков)
hdb_bki_other_active_pil_outstanding: 53.6% (41164 пропусков)
hdb_bki_total_auto_max_limit: 86.8% (66648 пропусков)
hdb_bki_total_ip_max_limit: 72.9% (55977 пропусков)
hdb_bki_total_micro_max_overdue: 75.4% (57872 пропусков)
label_500k_to_1M_share_r1: 55.7% (42776 пропусков)
label_Above_1M_share_r1: 55.7% (42776 пропусков)
label_Below_50k_share_r1: 55.7% (42776 пропусков)
loan_cnt: 75.0% (57584 пропусков)
loan_cur_amt: 86.0% (66054 пропусков)
max_balance_rur_amt_1m_af: 85.5% (65653 пропусков)
min_balance_rur_amt_1m_af: 85.5% (65653 пропусков)
min_balance_rur_amt_6m_af: 85.5% (65653 пропусков)
period_last_act_ad: 85.5% (65653 пропусков)
salary_6to12m_avg: 80.6% (61911 пропусков)
salary_median_in_gex_r1: 55.7% (42776 пропусков)
transaction_category_cash_percent_amt_2m: 66.7% (51200 пропусков)
transaction_category_fastfood_percent_cnt_2m: 55.0% (42217 пропусков)
transaction_category_restaurants_percent_amt_2m: 72.6% (55769 пропусков)
transaction_category_restaurants_percent_cnt_2m: 72.6% (55769 пропусков)
transaction_category_restaurants_sum_amt_m2: 72.6% (55769 пропусков)
transaction_category_supermarket_sum_amt_d15: 54.5% (41852 пропусков)
transaction_category_supermarket_sum_cnt_d15: 54.5% (41852 пропусков)
turn_fdep_db_avg_act_v2: 97.0% (74461 пропусков)
turn_fdep_db_avg_v2: 95.0% (72950 пропусков)
turn_fdep_db_sum_v2: 95.0% (72950 пропусков)
turn_save_cr_max_v2: 78.6% (60350 пропусков)
turn_save_db_min_v2: 78.6% (60350 пропусков)

Всего найдено: 83 столбцов

Удаляем столбцы из обоих наборов данных

In [9]:
all_columns_to_drop = list(columns_to_drop) + ['dt', 'avg_3m_no_cat', 'bki_active_auto_cnt',
                                              'bki_total_active_products', 'cntBlockWavg6m', 'days_after_last_request', 
                                              'device_iphone_avg', 'hdb_bki_active_pil_cnt', 'hdb_bki_last_product_days',
                                              'hdb_bki_total_cnt', 'hdb_bki_total_pil_max_del90', 'hdb_bki_total_products',
                                              'hdb_other_outstand_sum', 'tz_msk_timedelta', 'winback_cnt']

In [10]:
existing_columns_train = [col for col in all_columns_to_drop if col in data_train.columns]
existing_columns_test = [col for col in all_columns_to_drop if col in data_test.columns]

data_train_clean = data_train.drop(columns=existing_columns_train)
data_test_clean = data_test.drop(columns=existing_columns_test)

print(f"\nУдалено столбцов: {len(all_columns_to_drop)}")
print(f"Новый размер обучающих данных: {data_train_clean.shape}")
print(f"Новый размер тестовых данных: {data_test_clean.shape}")

Удалено столбцов: 98
Новый размер обучающих данных: (76786, 126)
Новый размер тестовых данных: (73214, 124)

In [11]:
print("Cтроки для удаления (>50%):")
rows_to_drop_ids = analyze_rows_statistics(data_train_clean)

Cтроки для удаления (>50%):
СТАТИСТИКА ПО СТРОКАМ:
Всего строк: 76786
Всего столбцов: 126
Максимально возможное пропусков в строке: 126

Распределение пропусков по строкам:
Строк без пропусков: 7340 (9.6%)
Строк с 50%+ пропусками: 13227 (17.2%)
Строк с 90%+ пропусками: 0 (0.0%)

Строк для удаления (порог 50%): 13227

In [12]:
existing_rows_train = [id for id in rows_to_drop_ids if id in data_train_clean.index]
data_train_clean = data_train_clean.drop(index=existing_rows_train)

# Изменение типов и заполнение пропусков

Исправим id, w, target

In [13]:
data_train_clean = convert_basic_columns(data_train_clean)
data_test = convert_basic_columns(data_test)

In [14]:
analyze_realistic_selection(data_train_clean)

Всего клиентов: 76672

ЗАПОЛНЕННОСТЬ ПРИЗНАКОВ:
  turn_cur_cr_avg_act_v2: 58986 (76.9%)
  hdb_bki_total_max_limit: 67316 (87.8%)
  hdb_bki_total_cc_max_limit: 62951 (82.1%)
  incomeValue: 63714 (83.1%)
  gender: 76672 (100.0%)
  avg_cur_cr_turn: 60120 (78.4%)
  adminarea: 57136 (74.5%)
  turn_cur_cr_avg_v2: 59340 (77.4%)
  turn_cur_cr_max_v2: 59340 (77.4%)
  hdb_bki_total_pil_max_limit: 61912 (80.7%)
  age: 76672 (100.0%)
  turn_cur_cr_sum_v2: 59340 (77.4%)
  turn_cur_db_sum_v2: 59340 (77.4%)
  turn_cur_db_avg_act_v2: 58489 (76.3%)
  curr_rur_amt_cm_avg: 58692 (76.5%)
  turn_cur_db_avg_v2: 59340 (77.4%)
  avg_cur_db_turn: 60120 (78.4%)
  hdb_bki_active_cc_max_limit: 56790 (74.1%)
  incomeValueCategory: 63714 (83.1%)
  avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate: 41822 (54.5%)
  avg_credit_turn_rur: 60120 (78.4%)
  by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona: 38596 (50.3%)
  turn_cur_cr_7avg_avg_v2: 59340 (77.4%)
  curbal_usd_amt_cm_avg: 75966 (99.1%)
  avg_by_category__amount__sum__cashflowcategory_name__supermarkety: 47681 (62.2%)
  avg_by_category__amount__sum__cashflowcategory_name__gipermarkety: 45042 (58.7%)
  city_smart_name: 67223 (87.7%)
  uniV5: 63714 (83.1%)
  turn_cur_db_max_v2: 59340 (77.4%)
  avg_by_category__amount__sum__cashflowcategory_name__kafe: 46837 (61.1%)
  turn_other_db_max_v2: 47966 (62.6%)
  turn_cur_cr_min_v2: 59340 (77.4%)
  turn_cur_db_min_v2: 59340 (77.4%)
  per_capita_income_rur_amt: 69289 (90.4%)
  avg_debet_turn_rur: 60120 (78.4%)
  hdb_relend_active_max_psk: 67207 (87.7%)
  dda_rur_amt_curr_v2: 73059 (95.3%)
  mob_cnt_days: 54605 (71.2%)
  avg_6m_money_transactions: 55042 (71.8%)
  transaction_category_supermarket_percent_cnt_2m: 42354 (55.2%)
  pil: 73011 (95.2%)
  hdb_bki_total_max_overdue_sum: 67160 (87.6%)
  avg_6m_clothing: 55042 (71.8%)
  avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi: 39614 (51.7%)
  addrref: 68134 (88.9%)
  bki_total_auto_cnt: 64865 (84.6%)
  hdb_outstand_sum: 67295 (87.8%)
  avg_3m_money_transactions: 55042 (71.8%)
  transaction_category_supermarket_sum_cnt_m3_4: 40242 (52.5%)
  blacklist_flag: 75966 (99.1%)
  bki_total_oth_cnt: 64865 (84.6%)
  hdb_relend_outstand_sum: 67300 (87.8%)
  total_rur_amt_cm_avg: 58692 (76.5%)
  mob_cover_days: 54605 (71.2%)
  curr_rur_amt_3m_avg: 70196 (91.6%)
  turn_cur_db_7avg_avg_v2: 59340 (77.4%)
  profit_income_out_rur_amt_12m: 76062 (99.2%)
  avg_6m_hotels: 55042 (71.8%)
  hdb_ovrd_sum: 67282 (87.8%)
  smsInWavg6m: 51884 (67.7%)
  avg_fdep_db_turn: 60120 (78.4%)
  curr_rur_amt_cm_avg_period_days_ago_v2: 73059 (95.3%)
  hdb_bki_total_ip_cnt: 67316 (87.8%)
  hdb_bki_active_cc_max_outstand: 56620 (73.8%)
  days_to_last_transaction: 66484 (86.7%)
  hdb_bki_total_pil_max_overdue: 61144 (79.7%)
  vert_pil_last_credit_step_screen_view_3m: 57211 (74.6%)
  acard: 73011 (95.2%)
  bki_total_il_max_limit: 47121 (61.5%)
  other_credits_count: 72946 (95.1%)
  profit_income_out_rur_amt_9m: 76062 (99.2%)
  dda_rur_amt_3m_avg: 70196 (91.6%)
  avg_amount_daily_transactions_90d: 51699 (67.4%)
  vert_has_app_ru_tinkoff_investing: 57211 (74.6%)
  transaction_category_supermarket_inc_cnt_2m: 42354 (55.2%)
  vert_pil_sms_success_3m: 57211 (74.6%)
  bki_total_products: 64865 (84.6%)
  avg_6m_all: 55042 (71.8%)
  summarur_1m_purch: 55042 (71.8%)
  diff_avg_cr_db_turn: 60120 (78.4%)
  turn_other_cr_avg_act_v2: 47286 (61.7%)
  cntVoiceOutMob6m: 51884 (67.7%)
  loanacc_rur_amt_cm_avg: 58692 (76.5%)
  transaction_category_supermarket_sum_cnt_m2: 42354 (55.2%)
  avg_fdep_cr_turn: 60120 (78.4%)
  bki_total_max_limit: 58957 (76.9%)
  turn_other_cr_sum_v2: 47966 (62.6%)
  client_active_flag: 75966 (99.1%)
  avg_by_category__amount__sum__cashflowcategory_name__produkty: 49907 (65.1%)
  curr_rur_amt_cm_avg_inc_v2: 73059 (95.3%)
  nonresident_flag: 76672 (100.0%)
  vert_has_app_ru_vtb_invest: 57211 (74.6%)
  cntRegionTripsWavg1m: 51884 (67.7%)
  vert_has_app_ru_cian_main: 57211 (74.6%)
  loanacc_rur_amt_curr_v2: 73059 (95.3%)
  vert_ghost_close_dpay3_last_days: 57211 (74.6%)
  vert_has_app_ru_raiffeisennews: 57211 (74.6%)
  vert_pil_loan_application_success_3m: 57211 (74.6%)
  vert_pil_fee_discount_change_3m: 57211 (74.6%)
  businessTelSubs: 51884 (67.7%)
  profit_income_out_rur_amt_l2m: 75966 (99.1%)
  avg_3m_healthcare_services: 55042 (71.8%)
  ovrd_sum: 47939 (62.5%)
  hdb_bki_total_active_products: 67316 (87.8%)
  hdb_bki_total_micro_cnt: 67316 (87.8%)
  mob_total_sessions: 54605 (71.2%)
  hdb_bki_total_cc_max_overdue: 62531 (81.6%)
  lifetimeComp: 51884 (67.7%)
  hdb_bki_total_pil_last_days: 61912 (80.7%)
  hdb_bki_active_pil_max_limit: 41851 (54.6%)
  avg_6m_restaurants: 55042 (71.8%)
  hdb_bki_total_pil_cnt: 67316 (87.8%)
  accountsalary_out_flag: 75966 (99.1%)
  express_rur_amt_cm_avg: 58692 (76.5%)
  loanacc_rur_amt_cm_avg_inc_v2: 73059 (95.3%)
  cred_dda_rur_amt_3m_avg: 70196 (91.6%)
  avg_3m_all: 55042 (71.8%)
  hdb_other_active_max_psk: 67178 (87.6%)
  total_sum: 47939 (62.5%)
  avg_6m_travel: 55042 (71.8%)
  avg_6m_government_services: 55042 (71.8%)
  hdb_bki_active_cc_max_overdue: 55658 (72.6%)
  total_rur_amt_cm_avg_period_days_ago_v2: 73059 (95.3%)

ТИПЫ ДАННЫХ:
  int32: 1 колонок
  float64: 22 колонок
  object: 103 колонок
    - turn_cur_cr_avg_act_v2: ['580744,47', '981258,71', '4710093,015']
    - incomeValue: ['22927,0', '41677,0', '70843,0']
    - gender: ['Мужской', 'Мужской', 'Женский']
    - avg_cur_cr_turn: ['88116,0', '194851,0', '1166149,0']
    - adminarea: ['Оренбургская область', 'Московская область', 'Московская область']

Анализируем проблемы

In [15]:
problems = identify_problem_features(data_train_clean)

⚠️  ПРОБЛЕМНЫЕ ПРИЗНАКИ ДЛЯ ОБРАБОТКИ:
Высокие пропуски (>30%): 24
   - avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate: 45.5% пропусков
   - by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona: 49.7% пропусков
   - avg_by_category__amount__sum__cashflowcategory_name__supermarkety: 37.8% пропусков
   - avg_by_category__amount__sum__cashflowcategory_name__gipermarkety: 41.3% пропусков
   - avg_by_category__amount__sum__cashflowcategory_name__kafe: 38.9% пропусков
   - turn_other_db_max_v2: 37.4% пропусков
   - transaction_category_supermarket_percent_cnt_2m: 44.8% пропусков
   - avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi: 48.3% пропусков
   - transaction_category_supermarket_sum_cnt_m3_4: 47.5% пропусков
   - smsInWavg6m: 32.3% пропусков
   - bki_total_il_max_limit: 38.5% пропусков
   - avg_amount_daily_transactions_90d: 32.6% пропусков
   - transaction_category_supermarket_inc_cnt_2m: 44.8% пропусков
   - turn_other_cr_avg_act_v2: 38.3% пропусков
   - cntVoiceOutMob6m: 32.3% пропусков
   - transaction_category_supermarket_sum_cnt_m2: 44.8% пропусков
   - turn_other_cr_sum_v2: 37.4% пропусков
   - avg_by_category__amount__sum__cashflowcategory_name__produkty: 34.9% пропусков
   - cntRegionTripsWavg1m: 32.3% пропусков
   - businessTelSubs: 32.3% пропусков
   - ovrd_sum: 37.5% пропусков
   - lifetimeComp: 32.3% пропусков
   - hdb_bki_active_pil_max_limit: 45.4% пропусков
   - total_sum: 37.5% пропусков
Строковые типы: 103
   - turn_cur_cr_avg_act_v2
   - incomeValue
   - gender
   - avg_cur_cr_turn
   - adminarea
   - turn_cur_cr_avg_v2
   - turn_cur_cr_max_v2
   - age
   - turn_cur_cr_sum_v2
   - turn_cur_db_sum_v2
   - turn_cur_db_avg_act_v2
   - curr_rur_amt_cm_avg
   - turn_cur_db_avg_v2
   - avg_cur_db_turn
   - incomeValueCategory
   - avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate
   - avg_credit_turn_rur
   - by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona
   - turn_cur_cr_7avg_avg_v2
   - curbal_usd_amt_cm_avg
   - avg_by_category__amount__sum__cashflowcategory_name__supermarkety
   - avg_by_category__amount__sum__cashflowcategory_name__gipermarkety
   - city_smart_name
   - uniV5
   - turn_cur_db_max_v2
   - avg_by_category__amount__sum__cashflowcategory_name__kafe
   - turn_other_db_max_v2
   - turn_cur_cr_min_v2
   - turn_cur_db_min_v2
   - per_capita_income_rur_amt
   - avg_debet_turn_rur
   - hdb_relend_active_max_psk
   - dda_rur_amt_curr_v2
   - mob_cnt_days
   - avg_6m_money_transactions
   - transaction_category_supermarket_percent_cnt_2m
   - pil
   - avg_6m_clothing
   - avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi
   - addrref
   - hdb_outstand_sum
   - avg_3m_money_transactions
   - transaction_category_supermarket_sum_cnt_m3_4
   - blacklist_flag
   - hdb_relend_outstand_sum
   - total_rur_amt_cm_avg
   - mob_cover_days
   - curr_rur_amt_3m_avg
   - turn_cur_db_7avg_avg_v2
   - profit_income_out_rur_amt_12m
   - avg_6m_hotels
   - hdb_ovrd_sum
   - smsInWavg6m
   - avg_fdep_db_turn
   - curr_rur_amt_cm_avg_period_days_ago_v2
   - days_to_last_transaction
   - vert_pil_last_credit_step_screen_view_3m
   - acard
   - other_credits_count
   - profit_income_out_rur_amt_9m
   - dda_rur_amt_3m_avg
   - avg_amount_daily_transactions_90d
   - vert_has_app_ru_tinkoff_investing
   - transaction_category_supermarket_inc_cnt_2m
   - vert_pil_sms_success_3m
   - avg_6m_all
   - summarur_1m_purch
   - diff_avg_cr_db_turn
   - turn_other_cr_avg_act_v2
   - cntVoiceOutMob6m
   - loanacc_rur_amt_cm_avg
   - transaction_category_supermarket_sum_cnt_m2
   - avg_fdep_cr_turn
   - turn_other_cr_sum_v2
   - client_active_flag
   - avg_by_category__amount__sum__cashflowcategory_name__produkty
   - curr_rur_amt_cm_avg_inc_v2
   - nonresident_flag
   - vert_has_app_ru_vtb_invest
   - cntRegionTripsWavg1m
   - vert_has_app_ru_cian_main
   - loanacc_rur_amt_curr_v2
   - vert_ghost_close_dpay3_last_days
   - vert_has_app_ru_raiffeisennews
   - vert_pil_loan_application_success_3m
   - vert_pil_fee_discount_change_3m
   - businessTelSubs
   - profit_income_out_rur_amt_l2m
   - avg_3m_healthcare_services
   - ovrd_sum
   - mob_total_sessions
   - lifetimeComp
   - avg_6m_restaurants
   - accountsalary_out_flag
   - express_rur_amt_cm_avg
   - loanacc_rur_amt_cm_avg_inc_v2
   - cred_dda_rur_amt_3m_avg
   - avg_3m_all
   - hdb_other_active_max_psk
   - total_sum
   - avg_6m_travel
   - avg_6m_government_services
   - total_rur_amt_cm_avg_period_days_ago_v2
Мало уникальных значений: 9

Преобразование типов данных

In [16]:
train_processed = convert_numeric_strings(data_train_clean.copy(), problems)
test_processed = convert_numeric_strings(data_test.copy(), problems)

In [17]:
train_processed, test_processed = quick_preprocess(train_processed, test_processed)

print(f"Тренировочные: {train_processed.shape}")
print(f"Тестовые: {test_processed.shape}")

Быстрая автоматическая обработка
Анализ данных

Отчет об анализе данных:
Числовые колонки: 20
   - hdb_bki_total_max_limit: float64, 26586 уникальных
   - hdb_bki_total_cc_max_limit: float64, 6382 уникальных
   - hdb_bki_total_pil_max_limit: float64, 27609 уникальных
   - hdb_bki_active_cc_max_limit: float64, 4479 уникальных
   - hdb_bki_total_max_overdue_sum: float64, 32962 уникальных
   - bki_total_auto_cnt: float64, 15 уникальных
   - bki_total_oth_cnt: float64, 24 уникальных
   - hdb_bki_total_ip_cnt: float64, 16 уникальных
   - hdb_bki_active_cc_max_outstand: float64, 42446 уникальных
   - hdb_bki_total_pil_max_overdue: float64, 29161 уникальных
   - bki_total_il_max_limit: float64, 25072 уникальных
   - bki_total_products: float64, 8 уникальных
   - bki_total_max_limit: float64, 23820 уникальных
   - hdb_bki_total_active_products: float64, 88 уникальных
   - hdb_bki_total_micro_cnt: float64, 149 уникальных
   - hdb_bki_total_cc_max_overdue: float64, 20756 уникальных
   - hdb_bki_total_pil_last_days: float64, 4442 уникальных
   - hdb_bki_active_pil_max_limit: float64, 22216 уникальных
   - hdb_bki_total_pil_cnt: float64, 91 уникальных
   - hdb_bki_active_cc_max_overdue: float64, 17819 уникальных
Строковые числа: 99
   - turn_cur_cr_avg_act_v2: ['580744,47', '981258,71', '4710093,015']
   - incomeValue: ['22927,0', '41677,0', '70843,0']
   - avg_cur_cr_turn: ['88116,0', '194851,0', '1166149,0']
   - turn_cur_cr_avg_v2: ['48395,3725', '163543,11833333332', '785015,5025']
   - turn_cur_cr_max_v2: ['59692,59', '139722,0', '1953021,38']
   - age: ['28,0', '34,0', '25,0']
   - turn_cur_cr_sum_v2: ['580744,47', '1962517,42', '9420186,03']
   - turn_cur_db_sum_v2: ['564717,72', '1961044,3099999996', '9516595,719999999']
   - turn_cur_db_avg_act_v2: ['564717,72', '980522,1549999998', '4758297,859999999']
   - curr_rur_amt_cm_avg: ['4101,0', '6317,0', '10390,0']
   - turn_cur_db_avg_v2: ['47059,81', '163420,35916666663', '793049,6433333332']
   - avg_cur_db_turn: ['82774,0', '194356,0', '1168955,0']
   - incomeValueCategory: ['2,0', '3,0', '4,0']
   - avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate: ['4520,54794520548', '20580,82191780822', '14178,082191780823']
   - avg_credit_turn_rur: ['96442,0', '217551,0', '1962930,0']
   - by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona: ['13084,681643835618', '41,50684931506849', '7071,369863013699']
   - turn_cur_cr_7avg_avg_v2: ['36839,44', '1500,0', '0,0']
   - curbal_usd_amt_cm_avg: ['84,0', '0,0', '0,0']
   - avg_by_category__amount__sum__cashflowcategory_name__supermarkety: ['1339,630684931507', '441,8424657534247', '372,81780821917806']
   - avg_by_category__amount__sum__cashflowcategory_name__gipermarkety: ['528,7167123287671', '1874,531506849315', '195,16684931506853']
   - uniV5: ['0,0564176', '0,0636772', '0,0043262']
   - turn_cur_db_max_v2: ['52000,0', '123889,0', '1953021,38']
   - avg_by_category__amount__sum__cashflowcategory_name__kafe: ['325,9150684931507', '43,97260273972603', '20,3013698630137']
   - turn_other_db_max_v2: ['52190,85', '18712,99', '146319,92']
   - turn_cur_cr_min_v2: ['580744,47', '539,0', '3642111,3099999996']
   - turn_cur_db_min_v2: ['564717,72', '539,0', '3738520,9999999995']
   - per_capita_income_rur_amt: ['44991,0', '59425,0', '61410,0']
   - avg_debet_turn_rur: ['99057,0', '219643,0', '1916079,0']
   - hdb_relend_active_max_psk: ['45,008', '292,0', '18,07']
   - dda_rur_amt_curr_v2: ['16028,0', '91,0', '0,0']
   - mob_cnt_days: ['71,0', '74,0', '2,0']
   - avg_6m_money_transactions: ['9167,0', '55366,0', '21667,0']
   - transaction_category_supermarket_percent_cnt_2m: ['0,6666666666666666', '0,2923076923076923', '0,7391304347826086']
   - pil: ['0,0', '0,0', '0,0']
   - avg_6m_clothing: ['6379,0', '0,0', '0,0']
   - avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi: ['254,7945205479452', '44966,889863013705', '1445,5068493150686']
   - hdb_outstand_sum: ['615425,095703125', '55186,0', '6496,0']
   - avg_3m_money_transactions: ['0,0', '89148,0', '43333,0']
   - transaction_category_supermarket_sum_cnt_m3_4: ['25,0', '16,0', '10,0']
   - blacklist_flag: ['0,0', '0,0', '0,0']
   - hdb_relend_outstand_sum: ['450609,095703125', '55186,0', '6496,0']
   - total_rur_amt_cm_avg: ['4124,0', '6317,0', '879674,0']
   - mob_cover_days: ['0,7888888888888889', '0,8222222222222222', '0,022222222222222223']
   - curr_rur_amt_3m_avg: ['11217,0', '6675,0', '10577,0']
   - turn_cur_db_7avg_avg_v2: ['10450,0', '1277,4866666666667', '3260,5']
   - profit_income_out_rur_amt_12m: ['510,5', '1658,4166666666667', '0,0']
   - avg_6m_hotels: ['0,0', '0,0', '0,0']
   - hdb_ovrd_sum: ['0,0', '48344,03125', '0,0']
   - smsInWavg6m: ['67,316', '151,9831', '116,5']
   - avg_fdep_db_turn: ['0,0', '0,0', '321007,0']
   - curr_rur_amt_cm_avg_period_days_ago_v2: ['7627,0', '12083,0', '0,0']
   - days_to_last_transaction: ['33,0', '9,0', '9,0']
   - vert_pil_last_credit_step_screen_view_3m: ['0,0', '0,0', '0,0']
   - acard: ['0,0', '0,0', '0,0']
   - other_credits_count: ['6,0', '3,0', '1,0']
   - profit_income_out_rur_amt_9m: ['680,6666666666666', '1975,2222222222222', '0,0']
   - dda_rur_amt_3m_avg: ['11217,0', '6675,0', '10577,0']
   - avg_amount_daily_transactions_90d: ['129,20044444444443', '5148,6253333333325', '1487,7777777777778']
   - vert_has_app_ru_tinkoff_investing: ['0,0', '0,0', '0,0']
   - transaction_category_supermarket_inc_cnt_2m: ['0,6822429906542056', '1,1915807560137457', '2,6517094017094016']
   - vert_pil_sms_success_3m: ['0,0', '0,0', '0,0']
   - avg_6m_all: ['38623,0', '109692,0', '22360,0']
   - summarur_1m_purch: ['0,0', '44553,0', '3900,0']
   - diff_avg_cr_db_turn: ['-2615,070000000007', '-2091,920000000042', '46850,94999999949']
   - turn_other_cr_avg_act_v2: ['75590,2125', '23865,54', '2538003,455000001']
   - cntVoiceOutMob6m: ['14381,2233', '281,9833', '244,8333']
   - loanacc_rur_amt_cm_avg: ['0,0', '0,0', '0,0']
   - transaction_category_supermarket_sum_cnt_m2: ['12,0', '19,0', '17,0']
   - avg_fdep_cr_turn: ['0,0', '0,0', '406027,0']
   - turn_other_cr_sum_v2: ['302360,85', '119327,7', '5076006,910000002']
   - client_active_flag: ['1,0', '1,0', '0,0']
   - avg_by_category__amount__sum__cashflowcategory_name__produkty: ['1404,423287671233', '4846,765479452055', '444,7964383561643']
   - curr_rur_amt_cm_avg_inc_v2: ['-5954,0', '-872,0', '0,0']
   - nonresident_flag: ['0,0', '0,0', '0,0']
   - vert_has_app_ru_vtb_invest: ['0,0', '0,0', '0,0']
   - cntRegionTripsWavg1m: ['0,0', '131,824', '0,7273']
   - vert_has_app_ru_cian_main: ['0,0', '0,0', '0,0']
   - loanacc_rur_amt_curr_v2: ['0,0', '0,0', '0,0']
   - vert_ghost_close_dpay3_last_days: ['0,0', '0,0', '0,0']
   - vert_has_app_ru_raiffeisennews: ['0,0', '0,0', '0,0']
   - vert_pil_loan_application_success_3m: ['0,0', '0,0', '0,0']
   - vert_pil_fee_discount_change_3m: ['2,0', '0,0', '0,0']
   - businessTelSubs: ['0,0', '0,0', '0,0']
   - profit_income_out_rur_amt_l2m: ['6607,0', '1439,0', '0,0']
   - avg_3m_healthcare_services: ['686,0', '624,0', '1300,0']
   - ovrd_sum: ['0,0', '0,0', '0,0']
   - mob_total_sessions: ['456,0', '477,0', '5,0']
   - lifetimeComp: ['80,0', '167,0', '135,0']
   - avg_6m_restaurants: ['1216,0', '42,0', '0,0']
   - accountsalary_out_flag: ['1,0', '1,0', '0,0']
   - express_rur_amt_cm_avg: ['0,0', '0,0', '0,0']
   - loanacc_rur_amt_cm_avg_inc_v2: ['0,0', '0,0', '0,0']
   - cred_dda_rur_amt_3m_avg: ['0,0', '0,0', '0,0']
   - avg_3m_all: ['3677,0', '154459,0', '44633,0']
   - hdb_other_active_max_psk: ['34,996', '292,0', '18,07']
   - total_sum: ['0,0', '0,0', '0,0']
   - avg_6m_travel: ['0,0', '0,0', '0,0']
   - avg_6m_government_services: ['0,0', '0,0', '44,0']
   - total_rur_amt_cm_avg_period_days_ago_v2: ['7627,0', '12083,0', '0,0']
Категориальные: 4
   - gender: 2 уникальных → ['Мужской', 'Женский']
   - adminarea: 85 уникальных → ['Оренбургская область', 'Московская область', 'Московская область']
   - city_smart_name: 105 уникальных → ['Бузулук', 'Курск', 'Москва']
   - addrref: 62 уникальных → ['Оренбургская область', 'Курская область', 'г. Москва']
Много пропусков (>30%): 24
   - avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate: 45.5% пропусков
   - by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona: 49.7% пропусков
   - avg_by_category__amount__sum__cashflowcategory_name__supermarkety: 37.8% пропусков
   - avg_by_category__amount__sum__cashflowcategory_name__gipermarkety: 41.3% пропусков
   - avg_by_category__amount__sum__cashflowcategory_name__kafe: 38.9% пропусков
   - turn_other_db_max_v2: 37.4% пропусков
   - transaction_category_supermarket_percent_cnt_2m: 44.8% пропусков
   - avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi: 48.3% пропусков
   - transaction_category_supermarket_sum_cnt_m3_4: 47.5% пропусков
   - smsInWavg6m: 32.3% пропусков
   - bki_total_il_max_limit: 38.5% пропусков
   - avg_amount_daily_transactions_90d: 32.6% пропусков
   - transaction_category_supermarket_inc_cnt_2m: 44.8% пропусков
   - turn_other_cr_avg_act_v2: 38.3% пропусков
   - cntVoiceOutMob6m: 32.3% пропусков
   - transaction_category_supermarket_sum_cnt_m2: 44.8% пропусков
   - turn_other_cr_sum_v2: 37.4% пропусков
   - avg_by_category__amount__sum__cashflowcategory_name__produkty: 34.9% пропусков
   - cntRegionTripsWavg1m: 32.3% пропусков
   - businessTelSubs: 32.3% пропусков
   - ovrd_sum: 37.5% пропусков
   - lifetimeComp: 32.3% пропусков
   - hdb_bki_active_pil_max_limit: 45.4% пропусков
   - total_sum: 37.5% пропусков
Преобразовано: turn_cur_cr_avg_act_v2 → numeric
Преобразовано: incomeValue → numeric
Преобразовано: avg_cur_cr_turn → numeric
Преобразовано: turn_cur_cr_avg_v2 → numeric
Преобразовано: turn_cur_cr_max_v2 → numeric
Преобразовано: age → numeric
Преобразовано: turn_cur_cr_sum_v2 → numeric
Преобразовано: turn_cur_db_sum_v2 → numeric
Преобразовано: turn_cur_db_avg_act_v2 → numeric
Преобразовано: curr_rur_amt_cm_avg → numeric
Преобразовано: turn_cur_db_avg_v2 → numeric
Преобразовано: avg_cur_db_turn → numeric
Преобразовано: incomeValueCategory → numeric
Преобразовано: avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate → numeric
Преобразовано: avg_credit_turn_rur → numeric
Преобразовано: by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona → numeric
Преобразовано: turn_cur_cr_7avg_avg_v2 → numeric
Преобразовано: curbal_usd_amt_cm_avg → numeric
Преобразовано: avg_by_category__amount__sum__cashflowcategory_name__supermarkety → numeric
Преобразовано: avg_by_category__amount__sum__cashflowcategory_name__gipermarkety → numeric
Преобразовано: uniV5 → numeric
Преобразовано: turn_cur_db_max_v2 → numeric
Преобразовано: avg_by_category__amount__sum__cashflowcategory_name__kafe → numeric
Преобразовано: turn_other_db_max_v2 → numeric
Преобразовано: turn_cur_cr_min_v2 → numeric
Преобразовано: turn_cur_db_min_v2 → numeric
Преобразовано: per_capita_income_rur_amt → numeric
Преобразовано: avg_debet_turn_rur → numeric
Преобразовано: hdb_relend_active_max_psk → numeric
Преобразовано: dda_rur_amt_curr_v2 → numeric
Преобразовано: mob_cnt_days → numeric
Преобразовано: avg_6m_money_transactions → numeric
Преобразовано: transaction_category_supermarket_percent_cnt_2m → numeric
Преобразовано: pil → numeric
Преобразовано: avg_6m_clothing → numeric
Преобразовано: avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi → numeric
Преобразовано: hdb_outstand_sum → numeric
Преобразовано: avg_3m_money_transactions → numeric
Преобразовано: transaction_category_supermarket_sum_cnt_m3_4 → numeric
Преобразовано: blacklist_flag → numeric
Преобразовано: hdb_relend_outstand_sum → numeric
Преобразовано: total_rur_amt_cm_avg → numeric
Преобразовано: mob_cover_days → numeric
Преобразовано: curr_rur_amt_3m_avg → numeric
Преобразовано: turn_cur_db_7avg_avg_v2 → numeric
Преобразовано: profit_income_out_rur_amt_12m → numeric
Преобразовано: avg_6m_hotels → numeric
Преобразовано: hdb_ovrd_sum → numeric
Преобразовано: smsInWavg6m → numeric
Преобразовано: avg_fdep_db_turn → numeric
Преобразовано: curr_rur_amt_cm_avg_period_days_ago_v2 → numeric
Преобразовано: days_to_last_transaction → numeric
Преобразовано: vert_pil_last_credit_step_screen_view_3m → numeric
Преобразовано: acard → numeric
Преобразовано: other_credits_count → numeric
Преобразовано: profit_income_out_rur_amt_9m → numeric
Преобразовано: dda_rur_amt_3m_avg → numeric
Преобразовано: avg_amount_daily_transactions_90d → numeric
Преобразовано: vert_has_app_ru_tinkoff_investing → numeric
Преобразовано: transaction_category_supermarket_inc_cnt_2m → numeric
Преобразовано: vert_pil_sms_success_3m → numeric
Преобразовано: avg_6m_all → numeric
Преобразовано: summarur_1m_purch → numeric
Преобразовано: diff_avg_cr_db_turn → numeric
Преобразовано: turn_other_cr_avg_act_v2 → numeric
Преобразовано: cntVoiceOutMob6m → numeric
Преобразовано: loanacc_rur_amt_cm_avg → numeric
Преобразовано: transaction_category_supermarket_sum_cnt_m2 → numeric
Преобразовано: avg_fdep_cr_turn → numeric
Преобразовано: turn_other_cr_sum_v2 → numeric
Преобразовано: client_active_flag → numeric
Преобразовано: avg_by_category__amount__sum__cashflowcategory_name__produkty → numeric
Преобразовано: curr_rur_amt_cm_avg_inc_v2 → numeric
Преобразовано: nonresident_flag → numeric
Преобразовано: vert_has_app_ru_vtb_invest → numeric
Преобразовано: cntRegionTripsWavg1m → numeric
Преобразовано: vert_has_app_ru_cian_main → numeric
Преобразовано: loanacc_rur_amt_curr_v2 → numeric
Преобразовано: vert_ghost_close_dpay3_last_days → numeric
Преобразовано: vert_has_app_ru_raiffeisennews → numeric
Преобразовано: vert_pil_loan_application_success_3m → numeric
Преобразовано: vert_pil_fee_discount_change_3m → numeric
Преобразовано: businessTelSubs → numeric
Преобразовано: profit_income_out_rur_amt_l2m → numeric
Преобразовано: avg_3m_healthcare_services → numeric
Преобразовано: ovrd_sum → numeric
Преобразовано: mob_total_sessions → numeric
Преобразовано: lifetimeComp → numeric
Преобразовано: avg_6m_restaurants → numeric
Преобразовано: accountsalary_out_flag → numeric
Преобразовано: express_rur_amt_cm_avg → numeric
Преобразовано: loanacc_rur_amt_cm_avg_inc_v2 → numeric
Преобразовано: cred_dda_rur_amt_3m_avg → numeric
Преобразовано: avg_3m_all → numeric
Преобразовано: hdb_other_active_max_psk → numeric
Преобразовано: total_sum → numeric
Преобразовано: avg_6m_travel → numeric
Преобразовано: avg_6m_government_services → numeric
Преобразовано: total_rur_amt_cm_avg_period_days_ago_v2 → numeric
Заполнены пропуски в 119 числовых колонках
Закодировано: gender (2 категорий)
Осталось пропусков: 37523
Оставшиеся пропуски заполнены
В тестовых данных появились новые колонки: {'loan_cnt', 'avg_by_category__amount__sum__cashflowcategory_name__set_supermarketov', 'max_balance_rur_amt_1m_af', 'min_balance_rur_amt_1m_af', 'dp_ils_uniq_companies_1y', 'dp_ils_ipkcurrentyear_currentyearpensfactor', 'label_Above_1M_share_r1', 'avg_3m_no_cat', 'dp_payoutincomedata_payout_max_6_month', 'dp_ils_accpayment_avg_12m', 'dp_ils_accpayment_avg_6m_current', 'dp_ils_days_ip_share_5y', 'by_category__amount__sum__eoperation_type_name__ishodjaschij_bystryj_platezh_sbp', 'avg_loan_cnt_with_insurance', 'loan_cur_amt', 'dp_ewb_dismissal_due_contract_violation_by_lb_cnt', 'hdb_bki_total_ip_max_limit', 'hdb_bki_last_product_days', 'dp_ils_accpayment_month_avg', 'dp_address_unique_regions', 'hdb_bki_total_cnt', 'label_Below_50k_share_r1', 'dp_ils_paymentssum_month_avg', 'salary_6to12m_avg', 'avg_balance_rur_amt_1m_af', 'dp_ils_accpayment_avg_6m', 'dp_ils_cnt_changes_1y', 'dp_ils_avg_salary_2y', 'transaction_category_fastfood_percent_cnt_2m', 'hdb_bki_total_products', 'amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate', 'dt', 'dp_ils_paymentssum_avg_6m', 'turn_fdep_db_avg_act_v2', 'calledCtnOutGroup', 'dp_payoutincomedata_payout_avg_3_month', 'days_after_last_request', 'transaction_category_restaurants_percent_cnt_2m', 'avg_by_category__amount__sum__cashflowcategory_name__odezhda', 'dp_ewb_last_employment_position', 'bki_total_ip_max_outstand', 'transaction_category_supermarket_sum_cnt_d15', 'dp_ils_employeers_cnt_last_month', 'device_iphone_avg', 'dp_ils_days_multiple_job_share_2y', 'bki_total_active_products', 'transaction_category_cash_percent_amt_2m', 'dp_ils_days_multiple_job_cnt_5y', 'label_500k_to_1M_share_r1', 'min_balance_rur_amt_6m_af', 'transaction_category_restaurants_sum_amt_m2', 'avg_by_category__amount__sum__cashflowcategory_name__oteli', 'amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__elektronnye_dengi', 'dp_payoutincomedata_payout_avg_prev_year', 'dp_payoutincomedata_payout_avg_6_month', 'transaction_category_restaurants_percent_amt_2m', 'cntOnnRinCallAvg6m', 'salary_median_in_gex_r1', 'turn_save_db_min_v2', 'transaction_category_supermarket_sum_amt_d15', 'by_category__amount__sum__eoperation_type_name__perevod_mezhdu_svoimi_schetami', 'by_category__amount__sum__eoperation_type_name__perevod_s_karty_na_kartu', 'dp_payoutincomedata_payout_sum_3_month', 'turn_fdep_db_avg_v2', 'dp_ils_avg_simultanious_jobs_5y', 'turn_save_cr_max_v2', 'hdb_bki_other_active_ip_outstanding', 'hdb_bki_total_pil_max_del90', 'turn_fdep_db_sum_v2', 'winback_cnt', 'dp_payoutincomedata_payout_max_3_month', 'dp_ils_salary_ratio_1y3y', 'dp_ewb_last_organization', 'period_last_act_ad', 'cntBlockWavg6m', 'avg_by_category__amount__sum__cashflowcategory_name__reklama_v_internete', 'avg_by_category__amount__sum__cashflowcategory_name__zarubezhnye_finansovye_operatsii', 'by_category__amount__sum__eoperation_type_name__platezh_za_mobilnyj_cherez_ps', 'dp_ils_days_from_last_doc', 'avg_by_category__amount__sum__cashflowcategory_name__platezhi_cherez_internet', 'dp_ils_paymentssum_avg_6m_current', 'dp_ils_avg_salary_1y', 'dp_ils_paymentssum_avg_12m', 'hdb_bki_other_active_pil_outstanding', 'dp_ils_total_seniority', 'hdb_bki_total_micro_max_overdue', 'dp_ils_avg_salary_3y', 'avg_by_category__amount__sum__cashflowcategory_name__puteshestvija', 'by_category__amount__sum__eoperation_type_name__vhodjaschij_bystryj_platezh_sbp', 'dp_ils_accpayment_avg_3m', 'avg_by_category__amount__sum__cashflowcategory_name__kosmetika', 'bki_active_auto_cnt', 'hdb_bki_total_auto_max_limit', 'tz_msk_timedelta', 'hdb_other_outstand_sum', 'first_salary_income', 'hdb_bki_active_pil_cnt', 'dp_ils_max_seniority'}
В тестовых данных отсутствуют колонки: {'target', 'w'}
Преобразовано: turn_cur_cr_avg_act_v2 → numeric
Преобразовано: incomeValue → numeric
Преобразовано: avg_cur_cr_turn → numeric
Преобразовано: turn_cur_cr_avg_v2 → numeric
Преобразовано: turn_cur_cr_max_v2 → numeric
Преобразовано: age → numeric
Преобразовано: turn_cur_cr_sum_v2 → numeric
Преобразовано: turn_cur_db_sum_v2 → numeric
Преобразовано: turn_cur_db_avg_act_v2 → numeric
Преобразовано: curr_rur_amt_cm_avg → numeric
Преобразовано: turn_cur_db_avg_v2 → numeric
Преобразовано: avg_cur_db_turn → numeric
Преобразовано: incomeValueCategory → numeric
Преобразовано: avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate → numeric
Преобразовано: avg_credit_turn_rur → numeric
Преобразовано: by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona → numeric
Преобразовано: turn_cur_cr_7avg_avg_v2 → numeric
Преобразовано: curbal_usd_amt_cm_avg → numeric
Преобразовано: avg_by_category__amount__sum__cashflowcategory_name__supermarkety → numeric
Преобразовано: avg_by_category__amount__sum__cashflowcategory_name__gipermarkety → numeric
Преобразовано: uniV5 → numeric
Преобразовано: turn_cur_db_max_v2 → numeric
Преобразовано: avg_by_category__amount__sum__cashflowcategory_name__kafe → numeric
Преобразовано: turn_other_db_max_v2 → numeric
Преобразовано: turn_cur_cr_min_v2 → numeric
Преобразовано: turn_cur_db_min_v2 → numeric
Преобразовано: per_capita_income_rur_amt → numeric

/Users/dataalph/Desktop/da_venv/lib/python3.10/site-packages/numpy/lib/_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/dataalph/Desktop/da_venv/lib/python3.10/site-packages/numpy/lib/_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [18]:
print("\n📈 Статистика после обработки:")
print(train_processed.info())

📈 Статистика после обработки:
<class 'pandas.core.frame.DataFrame'>
Index: 76672 entries, 114 to 76785
Columns: 126 entries, id to w
dtypes: float64(121), int32(1), int8(1), object(3)
memory usage: 73.5+ MB
None

Добавление зарплат по регионам

In [19]:
enricher = AdvancedSalaryEnricher(data_salary, region_col='Среднемесячная зп', salary_col='2023')
train_processed = enricher.fit_transform(train_processed)
test_processed = enricher.fit_transform(test_processed)

 СТАТИСТИКА МАТЧИНГА ЗАРПЛАТ:
 Найдены зарплаты для: 76672/76672 (100.0%)
 Диапазон зарплат: 28931 - 110771
 Средняя зарплата: 59504

 СТАТИСТИКА МАТЧИНГА ЗАРПЛАТ:
 Найдены зарплаты для: 73214/73214 (100.0%)
 Диапазон зарплат: 28931 - 110771
 Средняя зарплата: 59072

In [20]:
train_processed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76672 entries, 114 to 76785
Columns: 124 entries, id to salary
dtypes: float64(122), int32(1), int8(1)
memory usage: 72.3 MB

# Сохранение данных

In [21]:
train_processed.to_pickle('../data/df_train.pkl')
test_processed.to_pickle('../data/df_test.pkl')